package com.pe.lima.sg.entity.seguridad;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAcceso generated by hbm2java
 */
@Entity
@Table(name = "tbl_acceso", schema = "seg")
public class TblAcceso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoAcceso;
	private Integer codigoUsuario;
	private Date fechaCreacion;
	private String ipCreacion;

	public TblAcceso() {
	}

	public TblAcceso(int codigoAcceso) {
		this.codigoAcceso = codigoAcceso;
	}

	public TblAcceso(int codigoAcceso, Integer codigoUsuario, Date fechaCreacion, String ipCreacion) {
		this.codigoAcceso = codigoAcceso;
		this.codigoUsuario = codigoUsuario;
		this.fechaCreacion = fechaCreacion;
		this.ipCreacion = ipCreacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_acceso", unique = true, nullable = false)
	public int getCodigoAcceso() {
		return this.codigoAcceso;
	}

	public void setCodigoAcceso(int codigoAcceso) {
		this.codigoAcceso = codigoAcceso;
	}

	@Column(name = "codigo_usuario")
	public Integer getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(Integer codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

}
