package com.pe.lima.sg.entity.seguridad;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblIntento generated by hbm2java
 */
@Entity
@Table(name = "tbl_intento", schema = "seg")
public class TblIntento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoIntento;
	private String login;
	private String clave;
	private Date fechaCreacion;
	private String ipCreacion;

	public TblIntento() {
	}

	public TblIntento(int codigoIntento) {
		this.codigoIntento = codigoIntento;
	}

	public TblIntento(int codigoIntento, String login, String clave, Date fechaCreacion, String ipCreacion) {
		this.codigoIntento = codigoIntento;
		this.login = login;
		this.clave = clave;
		this.fechaCreacion = fechaCreacion;
		this.ipCreacion = ipCreacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_intento", unique = true, nullable = false)
	public int getCodigoIntento() {
		return this.codigoIntento;
	}

	public void setCodigoIntento(int codigoIntento) {
		this.codigoIntento = codigoIntento;
	}

	@Column(name = "login", length = 16)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "clave", length = 32)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

}
