package com.pe.lima.sg.entity.seguridad;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblOpcion generated by hbm2java
 */
@Entity
@Table(name = "tbl_opcion", schema = "seg")
public class TblOpcion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoOpcion;
	private String nombre;
	private String ruta;
	private Integer modulo;
	private Integer nivel;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Set<TblPerfilOpcion> tblPerfilOpcions = new HashSet<TblPerfilOpcion>(0);
	private boolean seleccionado;
	public TblOpcion() {
	}

	public TblOpcion(int codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	public TblOpcion(int codigoOpcion, String nombre, String ruta, Integer modulo, Integer nivel, String estado,
			Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion, Set<TblPerfilOpcion> tblPerfilOpcions) {
		this.codigoOpcion = codigoOpcion;
		this.nombre = nombre;
		this.ruta = ruta;
		this.modulo = modulo;
		this.nivel = nivel;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tblPerfilOpcions = tblPerfilOpcions;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_opcion", unique = true, nullable = false)
	public int getCodigoOpcion() {
		return this.codigoOpcion;
	}

	public void setCodigoOpcion(int codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	@Column(name = "nombre", length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ruta", length = 256)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "modulo")
	public Integer getModulo() {
		return this.modulo;
	}

	public void setModulo(Integer modulo) {
		this.modulo = modulo;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOpcion")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblPerfilOpcion> getTblPerfilOpcions() {
		return this.tblPerfilOpcions;
	}

	public void setTblPerfilOpcions(Set<TblPerfilOpcion> tblPerfilOpcions) {
		this.tblPerfilOpcions = tblPerfilOpcions;
	}
	/**
	 * @return the seleccionado
	 */
	@Transient
	public boolean isSeleccionado() {
		return seleccionado;
	}

	/**
	 * @param seleccionado the seleccionado to set
	 */
	public void setSeleccionado(boolean seleccionado) {
		this.seleccionado = seleccionado;
	}	
}
