package com.pe.lima.sg.entity.seguridad;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPerfilOpcion generated by hbm2java
 */
@Entity
@Table(name = "tbl_perfil_opcion", schema = "seg")
public class TblPerfilOpcion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private TblPerfilOpcionId id;
	private TblOpcion tblOpcion;
	private TblPerfil tblPerfil;
	private String privilegio;
	private Integer usuarioCreacion;
	private Date fechaCreacion;
	private String ipCreacion;

	public TblPerfilOpcion() {
	}

	public TblPerfilOpcion(TblPerfilOpcionId id, TblOpcion tblOpcion, TblPerfil tblPerfil) {
		this.id = id;
		this.tblOpcion = tblOpcion;
		this.tblPerfil = tblPerfil;
	}

	public TblPerfilOpcion(TblPerfilOpcionId id, TblOpcion tblOpcion, TblPerfil tblPerfil, String privilegio,
			Integer usuarioCreacion, Date fechaCreacion, String ipCreacion) {
		this.id = id;
		this.tblOpcion = tblOpcion;
		this.tblPerfil = tblPerfil;
		this.privilegio = privilegio;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.ipCreacion = ipCreacion;
	}

	@EmbeddedId
	
	@AttributeOverrides({
			@AttributeOverride(name = "codigoPerfil", column = @Column(name = "codigo_perfil", nullable = false)),
			@AttributeOverride(name = "codigoOpcion", column = @Column(name = "codigo_opcion", nullable = false)) })
	public TblPerfilOpcionId getId() {
		return this.id;
	}

	public void setId(TblPerfilOpcionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_opcion", nullable = false, insertable = false, updatable = false)
	public TblOpcion getTblOpcion() {
		return this.tblOpcion;
	}

	public void setTblOpcion(TblOpcion tblOpcion) {
		this.tblOpcion = tblOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_perfil", nullable = false, insertable = false, updatable = false)
	public TblPerfil getTblPerfil() {
		return this.tblPerfil;
	}

	public void setTblPerfil(TblPerfil tblPerfil) {
		this.tblPerfil = tblPerfil;
	}

	@Column(name = "privilegio", length = 8)
	public String getPrivilegio() {
		return this.privilegio;
	}

	public void setPrivilegio(String privilegio) {
		this.privilegio = privilegio;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

}
