package com.pe.lima.sg.entity.seguridad;
// Generated 8/11/2020 09:29:59 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblPermiso generated by hbm2java
 */
@Entity
@Table(name = "tbl_permiso", schema = "seg")
public class TblPermiso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoPermiso;
	private String nombreModulo;
	private String nombreOpcion;
	private String descripcion;
	private String code;
	private String estado;
	private Integer usuarioCreacion;
	private Date fechaCreacion;
	private String ipCreacion;
	private Set<TblUsuarioPermiso> tblUsuarioPermisos = new HashSet<TblUsuarioPermiso>(0);

	public TblPermiso() {
	}

	public TblPermiso(int codigoPermiso) {
		this.codigoPermiso = codigoPermiso;
	}

	public TblPermiso(int codigoPermiso, String nombreModulo, String nombreOpcion, String descripcion, String code, String estado,
			Integer usuarioCreacion, Date fechaCreacion, String ipCreacion, Set<TblUsuarioPermiso> tblUsuarioPermisos) {
		this.codigoPermiso = codigoPermiso;
		this.nombreModulo = nombreModulo;
		this.nombreOpcion = nombreOpcion;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.ipCreacion = ipCreacion;
		this.tblUsuarioPermisos = tblUsuarioPermisos;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_permiso", unique = true, nullable = false)
	public int getCodigoPermiso() {
		return this.codigoPermiso;
	}

	public void setCodigoPermiso(int codigoPermiso) {
		this.codigoPermiso = codigoPermiso;
	}

	@Column(name = "nombre_modulo", length = 64)
	public String getNombreModulo() {
		return this.nombreModulo;
	}

	public void setNombreModulo(String nombreModulo) {
		this.nombreModulo = nombreModulo;
	}

	@Column(name = "nombre_opcion", length = 64)
	public String getNombreOpcion() {
		return this.nombreOpcion;
	}

	public void setNombreOpcion(String nombreOpcion) {
		this.nombreOpcion = nombreOpcion;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPermiso")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblUsuarioPermiso> getTblUsuarioPermisos() {
		return this.tblUsuarioPermisos;
	}

	public void setTblUsuarioPermisos(Set<TblUsuarioPermiso> tblUsuarioPermisos) {
		this.tblUsuarioPermisos = tblUsuarioPermisos;
	}

	@Column(name = "code", length = 8)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
