package com.pe.lima.sg.entity.seguridad;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblPerfilOpcionId generated by hbm2java
 */
@Embeddable
public class TblPerfilOpcionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int codigoPerfil;
	private int codigoOpcion;

	public TblPerfilOpcionId() {
	}

	public TblPerfilOpcionId(int codigoPerfil, int codigoOpcion) {
		this.codigoPerfil = codigoPerfil;
		this.codigoOpcion = codigoOpcion;
	}

	@Column(name = "codigo_perfil", nullable = false)
	public int getCodigoPerfil() {
		return this.codigoPerfil;
	}

	public void setCodigoPerfil(int codigoPerfil) {
		this.codigoPerfil = codigoPerfil;
	}

	@Column(name = "codigo_opcion", nullable = false)
	public int getCodigoOpcion() {
		return this.codigoOpcion;
	}

	public void setCodigoOpcion(int codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPerfilOpcionId))
			return false;
		TblPerfilOpcionId castOther = (TblPerfilOpcionId) other;

		return (this.getCodigoPerfil() == castOther.getCodigoPerfil())
				&& (this.getCodigoOpcion() == castOther.getCodigoOpcion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPerfil();
		result = 37 * result + this.getCodigoOpcion();
		return result;
	}

}
