package com.pe.lima.sg.entity.seguridad;
// Generated 8/11/2020 09:29:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUsuarioPermiso generated by hbm2java
 */
@Entity
@Table(name = "tbl_usuario_permiso", schema = "seg")
public class TblUsuarioPermiso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private TblPermiso tblPermiso;
	private TblUsuario tblUsuario;

	public TblUsuarioPermiso() {
	}

	public TblUsuarioPermiso(int id, TblPermiso tblPermiso, TblUsuario tblUsuario) {
		this.id = id;
		this.tblPermiso = tblPermiso;
		this.tblUsuario = tblUsuario;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_permiso", nullable = false)
	public TblPermiso getTblPermiso() {
		return this.tblPermiso;
	}

	public void setTblPermiso(TblPermiso tblPermiso) {
		this.tblPermiso = tblPermiso;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_usuario", nullable = false)
	public TblUsuario getTblUsuario() {
		return this.tblUsuario;
	}

	public void setTblUsuario(TblUsuario tblUsuario) {
		this.tblUsuario = tblUsuario;
	}

}
