package com.pe.lima.sg.entity.caja;
// Generated 11/03/2018 12:42:03 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCajaChica generated by hbm2java
 */
@Entity
@Table(name = "tbl_caja_chica", schema = "caj")
public class TblCajaChica implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoCajaChica;
	private String nombre;
	private Integer anio;
	private Integer mes;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal totalIngresoSoles	= new BigDecimal("0");
	private BigDecimal totalSalidaSoles		= new BigDecimal("0");
	private BigDecimal saldoSoles			= new BigDecimal("0");
	private BigDecimal totalIngresoDolares	= new BigDecimal("0");
	private BigDecimal totalSalidaDolares	= new BigDecimal("0");
	private BigDecimal saldoDolares			= new BigDecimal("0");
	private String estado;
	private Integer estadoCaja;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Set<TblDetalleCajaChica> tblDetalleCajaChicas = new HashSet<TblDetalleCajaChica>(0);

	public TblCajaChica() {
	}

	public TblCajaChica(int codigoCajaChica) {
		this.codigoCajaChica = codigoCajaChica;
	}

	public TblCajaChica(int codigoCajaChica, String nombre, Integer anio, Integer mes, Date fechaInicio, Date fechaFin,
			BigDecimal totalIngresoSoles, BigDecimal totalSalidaSoles, BigDecimal saldoSoles,
			BigDecimal totalIngresoDolares, BigDecimal totalSalidaDolares, BigDecimal saldoDolares, String estado, Integer estadoCaja, Integer usuarioCreacion,
			Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion, String ipCreacion,
			String ipModificacion, Set<TblDetalleCajaChica> tblDetalleCajaChicas) {
		this.codigoCajaChica = codigoCajaChica;
		this.nombre = nombre;
		this.anio = anio;
		this.mes = mes;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.totalIngresoSoles = totalIngresoSoles;
		this.totalSalidaSoles = totalSalidaSoles;
		this.saldoSoles = saldoSoles;
		this.totalIngresoDolares = totalIngresoDolares;
		this.totalSalidaDolares = totalSalidaDolares;
		this.saldoDolares = saldoDolares;
		this.estado = estado;
		this.estadoCaja = estadoCaja;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tblDetalleCajaChicas = tblDetalleCajaChicas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_caja_chica", unique = true, nullable = false)
	public int getCodigoCajaChica() {
		return this.codigoCajaChica;
	}

	public void setCodigoCajaChica(int codigoCajaChica) {
		this.codigoCajaChica = codigoCajaChica;
	}

	@Column(name = "nombre", length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "total_ingreso_soles", precision = 12)
	public BigDecimal getTotalIngresoSoles() {
		return this.totalIngresoSoles;
	}

	public void setTotalIngresoSoles(BigDecimal totalIngresoSoles) {
		this.totalIngresoSoles = totalIngresoSoles;
	}

	@Column(name = "total_salida_soles", precision = 12)
	public BigDecimal getTotalSalidaSoles() {
		return this.totalSalidaSoles;
	}

	public void setTotalSalidaSoles(BigDecimal totalSalidaSoles) {
		this.totalSalidaSoles = totalSalidaSoles;
	}

	@Column(name = "saldo_soles", precision = 12)
	public BigDecimal getSaldoSoles() {
		return this.saldoSoles;
	}

	public void setSaldoSoles(BigDecimal saldoSoles) {
		this.saldoSoles = saldoSoles;
	}

	@Column(name = "total_ingreso_dolares")
	public BigDecimal getTotalIngresoDolares() {
		return this.totalIngresoDolares;
	}

	public void setTotalIngresoDolares(BigDecimal totalIngresoDolares) {
		this.totalIngresoDolares = totalIngresoDolares;
	}

	@Column(name = "total_salida_dolares")
	public BigDecimal getTotalSalidaDolares() {
		return this.totalSalidaDolares;
	}

	public void setTotalSalidaDolares(BigDecimal totalSalidaDolares) {
		this.totalSalidaDolares = totalSalidaDolares;
	}

	@Column(name = "saldo_dolares")
	public BigDecimal getSaldoDolares() {
		return this.saldoDolares;
	}

	public void setSaldoDolares(BigDecimal saldoDolares) {
		this.saldoDolares = saldoDolares;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCajaChica")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblDetalleCajaChica> getTblDetalleCajaChicas() {
		return this.tblDetalleCajaChicas;
	}

	public void setTblDetalleCajaChicas(Set<TblDetalleCajaChica> tblDetalleCajaChicas) {
		this.tblDetalleCajaChicas = tblDetalleCajaChicas;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "estado_caja")
	public Integer getEstadoCaja() {
		return estadoCaja;
	}

	public void setEstadoCaja(Integer estadoCaja) {
		this.estadoCaja = estadoCaja;
	}

}
