package com.pe.lima.sg.entity.caja;
// Generated 11/10/2017 10:08:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TblCobro generated by hbm2java
 */
@Entity
@Table(name = "tbl_cobro", schema = "caj")
public class TblCobro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoCobro;
	private TblCxcDocumento tblCxcDocumento;
	private TblDesembolso tblDesembolso;
	private String tipoCobro;
	private Date fechaCobro;
	private BigDecimal montoSoles;
	private BigDecimal montoDolares;
	private String tipoMoneda;
	private BigDecimal tipoCambio;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblCobro() {
	}

	public TblCobro(int codigoCobro, TblCxcDocumento tblCxcDocumento) {
		this.codigoCobro = codigoCobro;
		this.tblCxcDocumento = tblCxcDocumento;
	}

	public TblCobro(int codigoCobro, TblCxcDocumento tblCxcDocumento, TblDesembolso tblDesembolso, String tipoCobro, Date fechaCobro,
			BigDecimal montoSoles, BigDecimal montoDolares, String tipoMoneda, BigDecimal tipoCambio, String estado,
			Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion) {
		this.codigoCobro = codigoCobro;
		this.tblCxcDocumento = tblCxcDocumento;
		this.tblDesembolso = tblDesembolso;
		this.tipoCobro = tipoCobro;
		this.fechaCobro = fechaCobro;
		this.montoSoles = montoSoles;
		this.montoDolares = montoDolares;
		this.tipoMoneda = tipoMoneda;
		this.tipoCambio = tipoCambio;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_cobro", unique = true, nullable = false)
	public int getCodigoCobro() {
		return this.codigoCobro;
	}

	public void setCodigoCobro(int codigoCobro) {
		this.codigoCobro = codigoCobro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cxc_doc", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblCxcDocumento getTblCxcDocumento() {
		return this.tblCxcDocumento;
	}

	public void setTblCxcDocumento(TblCxcDocumento tblCxcDocumento) {
		this.tblCxcDocumento = tblCxcDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_desembolso")
	public TblDesembolso getTblDesembolso() {
		return this.tblDesembolso;
	}

	public void setTblDesembolso(TblDesembolso tblDesembolso) {
		this.tblDesembolso = tblDesembolso;
	}

	@Column(name = "tipo_cobro", length = 8)
	public String getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(String tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cobro", length = 13)
	public Date getFechaCobro() {
		return this.fechaCobro;
	}

	public void setFechaCobro(Date fechaCobro) {
		this.fechaCobro = fechaCobro;
	}

	@Column(name = "monto_soles", precision = 12)
	public BigDecimal getMontoSoles() {
		return this.montoSoles;
	}

	public void setMontoSoles(BigDecimal montoSoles) {
		this.montoSoles = montoSoles;
	}

	@Column(name = "monto_dolares", precision = 12)
	public BigDecimal getMontoDolares() {
		return this.montoDolares;
	}

	public void setMontoDolares(BigDecimal montoDolares) {
		this.montoDolares = montoDolares;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_cambio", precision = 12)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

}
