package com.pe.lima.sg.entity.caja;
// Generated 26/11/2017 05:22:50 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCxcBitacora generated by hbm2java
 */
@Entity
@Table(name = "tbl_cxc_bitacora", schema = "caj")
public class TblCxcBitacora implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoCxcBitacora;
	private Integer anio;
	private Integer mes;
	private String tipoOperacion;
	private String tipoCobro;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String resultado;
	private Set<TblCxcDocumento> tblCxcDocumentos = new HashSet<TblCxcDocumento>(0);
	private Integer codigoContrato;
	
	
	public TblCxcBitacora() {
	}

	public TblCxcBitacora(int codigoCxcBitacora) {
		this.codigoCxcBitacora = codigoCxcBitacora;
	}

	public TblCxcBitacora(int codigoCxcBitacora, Integer anio, Integer mes,String tipoOperacion, String tipoCobro,
			String estado, Integer usuarioCreacion, Integer usuarioModificacion,
			Date fechaCreacion, Date fechaModificacion, String ipCreacion, String ipModificacion,
			String resultado, 
			Set<TblCxcDocumento> tblCxcDocumentos, Integer codigoContrato) {
		this.codigoCxcBitacora = codigoCxcBitacora;
		this.anio = anio;
		this.mes = mes;
		this.tipoOperacion = tipoOperacion;
		this.tipoCobro = tipoCobro;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.resultado = resultado;
		this.tblCxcDocumentos = tblCxcDocumentos;
		this.codigoContrato = codigoContrato;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_cxc_bitacora", unique = true, nullable = false)
	public int getCodigoCxcBitacora() {
		return this.codigoCxcBitacora;
	}

	public void setCodigoCxcBitacora(int codigoCxcBitacora) {
		this.codigoCxcBitacora = codigoCxcBitacora;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "tipo_operacion", length = 8)
	public String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	@Column(name = "tipo_cobro", length = 8)
	public String getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(String tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "resultado", length = 512)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCxcBitacora")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblCxcDocumento> getTblCxcDocumentos() {
		return this.tblCxcDocumentos;
	}

	public void setTblCxcDocumentos(Set<TblCxcDocumento> tblCxcDocumentos) {
		this.tblCxcDocumentos = tblCxcDocumentos;
	}

	@Column(name = "codigo_contrato")
	public Integer getCodigoContrato() {
		return codigoContrato;
	}

	public void setCodigoContrato(Integer codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

}
