package com.pe.lima.sg.entity.caja;
// Generated 26/11/2017 05:22:50 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCxcDocumento generated by hbm2java
 */
@Entity
@Table(name = "tbl_cxc_documento", schema = "caj")
public class TblCxcDocumento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoCxcDoc;
	private TblCxcBitacora tblCxcBitacora;
	private Integer codigoReferencia;
	private String tipoReferencia;
	private BigDecimal montoGenerado;
	private BigDecimal montoContrato;
	private BigDecimal montoCobrado;
	private BigDecimal saldo;
	private String tipoMoneda;
	private String tipoDocumento;
	private Integer anio;
	private Integer mes;
	private Date fechaFin;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String tipoComprobante;
	private String serieComprobante;
	private String numeroComprobante;
	private Set<TblSunatCabecera> tblSunatCabeceras = new HashSet<TblSunatCabecera>(0);
	private Set<TblCobro> tblCobros = new HashSet<TblCobro>(0);
	private Integer codigoContrato;
	private String nombre;
	private String fechaFinNombre;
	private Integer codigoComprobante;
	private Integer codigoRenovacion;
	
	public TblCxcDocumento() {
	}

	public TblCxcDocumento(int codigoCxcDoc, TblCxcBitacora tblCxcBitacora) {
		this.codigoCxcDoc = codigoCxcDoc;
		this.tblCxcBitacora = tblCxcBitacora;
	}

	public TblCxcDocumento(int codigoCxcDoc, TblCxcBitacora tblCxcBitacora, Integer codigoReferencia,
			String tipoReferencia, BigDecimal montoGenerado, BigDecimal montoContrato, BigDecimal montoCobrado,
			BigDecimal saldo, String tipoMoneda, String tipoDocumento, Integer anio, Integer mes, Date fechaFin, String estado, Integer usuarioCreacion,
			Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion, String ipCreacion,
			String ipModificacion, String tipoComprobante, String serieComprobante, String numeroComprobante,
			Set<TblSunatCabecera> tblSunatCabeceras, Set<TblCobro> tblCobros, Integer codigoContrato,String nombre, String fechaFinNombre) {
		this.codigoCxcDoc = codigoCxcDoc;
		this.tblCxcBitacora = tblCxcBitacora;
		this.codigoReferencia = codigoReferencia;
		this.tipoReferencia = tipoReferencia;
		this.montoGenerado = montoGenerado;
		this.montoContrato = montoContrato;
		this.montoCobrado = montoCobrado;
		this.saldo = saldo;
		this.tipoMoneda = tipoMoneda;
		this.tipoDocumento = tipoDocumento;
		this.anio = anio;
		this.mes = mes;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tipoComprobante = tipoComprobante;
		this.serieComprobante = serieComprobante;
		this.numeroComprobante = numeroComprobante;
		this.tblSunatCabeceras = tblSunatCabeceras;
		this.tblCobros = tblCobros;
		this.codigoContrato = codigoContrato;
		this.nombre = nombre;
		this.fechaFinNombre = fechaFinNombre;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_cxc_doc", unique = true, nullable = false)
	public int getCodigoCxcDoc() {
		return this.codigoCxcDoc;
	}

	public void setCodigoCxcDoc(int codigoCxcDoc) {
		this.codigoCxcDoc = codigoCxcDoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cxc_bitacora", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblCxcBitacora getTblCxcBitacora() {
		return this.tblCxcBitacora;
	}

	public void setTblCxcBitacora(TblCxcBitacora tblCxcBitacora) {
		this.tblCxcBitacora = tblCxcBitacora;
	}

	@Column(name = "codigo_referencia")
	public Integer getCodigoReferencia() {
		return this.codigoReferencia;
	}

	public void setCodigoReferencia(Integer codigoReferencia) {
		this.codigoReferencia = codigoReferencia;
	}

	@Column(name = "tipo_referencia", length = 8)
	public String getTipoReferencia() {
		return this.tipoReferencia;
	}

	public void setTipoReferencia(String tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	@Column(name = "monto_generado", precision = 12)
	public BigDecimal getMontoGenerado() {
		return this.montoGenerado;
	}

	public void setMontoGenerado(BigDecimal montoGenerado) {
		this.montoGenerado = montoGenerado;
	}

	@Column(name = "monto_contrato", precision = 12)
	public BigDecimal getMontoContrato() {
		return this.montoContrato;
	}

	public void setMontoContrato(BigDecimal montoContrato) {
		this.montoContrato = montoContrato;
	}

	@Column(name = "monto_cobrado", precision = 12)
	public BigDecimal getMontoCobrado() {
		return this.montoCobrado;
	}

	public void setMontoCobrado(BigDecimal montoCobrado) {
		this.montoCobrado = montoCobrado;
	}

	@Column(name = "saldo", precision = 12)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_documento", length = 8)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "tipo_comprobante", length = 2)
	public String getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(String tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	@Column(name = "serie_comprobante", length = 4)
	public String getSerieComprobante() {
		return this.serieComprobante;
	}

	public void setSerieComprobante(String serieComprobante) {
		this.serieComprobante = serieComprobante;
	}

	@Column(name = "numero_comprobante", length = 8)
	public String getNumeroComprobante() {
		return this.numeroComprobante;
	}

	public void setNumeroComprobante(String numeroComprobante) {
		this.numeroComprobante = numeroComprobante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCxcDocumento")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblSunatCabecera> getTblSunatCabeceras() {
		return this.tblSunatCabeceras;
	}

	public void setTblSunatCabeceras(Set<TblSunatCabecera> tblSunatCabeceras) {
		this.tblSunatCabeceras = tblSunatCabeceras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCxcDocumento")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblCobro> getTblCobros() {
		return this.tblCobros;
	}

	public void setTblCobros(Set<TblCobro> tblCobros) {
		this.tblCobros = tblCobros;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "codigo_contrato")
	public Integer getCodigoContrato() {
		return codigoContrato;
	}

	public void setCodigoContrato(Integer codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

	@Column(name = "nombre", length = 256)
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "fecha_fin_nombre", length = 64)
	public String getFechaFinNombre() {
		return fechaFinNombre;
	}

	public void setFechaFinNombre(String fechaFinNombre) {
		this.fechaFinNombre = fechaFinNombre;
	}

	
	@Column(name = "codigo_comprobante")
	public Integer getCodigoComprobante() {
		return codigoComprobante;
	}

	public void setCodigoComprobante(Integer codigoComprobante) {
		this.codigoComprobante = codigoComprobante;
	}

	@Column(name = "codigo_renovacion")
	public Integer getCodigoRenovacion() {
		return codigoRenovacion;
	}

	public void setCodigoRenovacion(Integer codigoRenovacion) {
		this.codigoRenovacion = codigoRenovacion;
	}

}
