package com.pe.lima.sg.entity.caja;
// Generated 11/03/2018 12:42:03 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.entity.mantenimiento.TblConcepto;

/**
 * TblDetalleCajaChica generated by hbm2java
 */
@Entity
@Table(name = "tbl_detalle_caja_chica", schema = "caj")
public class TblDetalleCajaChica implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoDetalleCchica;
	private TblCajaChica tblCajaChica;
	private TblConcepto tblConcepto;
	private String descripcion;
	private Date fecha;
	private BigDecimal montoSoles;
	private BigDecimal tipoCambio;
	private BigDecimal montoDolares;
	private String tipoMoneda;
	private String tipoOperacion;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblDetalleCajaChica() {
	}

	public TblDetalleCajaChica(int codigoDetalleCchica, TblCajaChica tblCajaChica, TblConcepto tblConcepto) {
		this.codigoDetalleCchica = codigoDetalleCchica;
		this.tblCajaChica = tblCajaChica;
		this.tblConcepto = tblConcepto;
	}

	public TblDetalleCajaChica(int codigoDetalleCchica, TblCajaChica tblCajaChica, TblConcepto tblConcepto,
			String descripcion, Date fecha, BigDecimal montoSoles, BigDecimal tipoCambio, BigDecimal montoDolares,String tipoMoneda,String tipoOperacion,
			String estado, Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion) {
		this.codigoDetalleCchica = codigoDetalleCchica;
		this.tblCajaChica = tblCajaChica;
		this.tblConcepto = tblConcepto;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.montoSoles = montoSoles;
		this.tipoCambio = tipoCambio;
		this.montoDolares = montoDolares;
		this.tipoMoneda = tipoMoneda;
		this.tipoOperacion = tipoOperacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_detalle_cchica", unique = true, nullable = false)
	public int getCodigoDetalleCchica() {
		return this.codigoDetalleCchica;
	}

	public void setCodigoDetalleCchica(int codigoDetalleCchica) {
		this.codigoDetalleCchica = codigoDetalleCchica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_caja_chica", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblCajaChica getTblCajaChica() {
		return this.tblCajaChica;
	}

	public void setTblCajaChica(TblCajaChica tblCajaChica) {
		this.tblCajaChica = tblCajaChica;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_concepto", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblConcepto getTblConcepto() {
		return this.tblConcepto;
	}

	public void setTblConcepto(TblConcepto tblConcepto) {
		this.tblConcepto = tblConcepto;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "monto_soles", precision = 12)
	public BigDecimal getMontoSoles() {
		return this.montoSoles;
	}

	public void setMontoSoles(BigDecimal montoSoles) {
		this.montoSoles = montoSoles;
	}

	@Column(name = "tipo_cambio", precision = 12)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "monto_dolares", precision = 12)
	public BigDecimal getMontoDolares() {
		return this.montoDolares;
	}

	public void setMontoDolares(BigDecimal montoDolares) {
		this.montoDolares = montoDolares;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_operacion", length = 2)
	public String getTipoOperacion() {
		return tipoOperacion;
	}

	public void setTipoOperacion(String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

}
