package com.pe.lima.sg.entity.caja;
// Generated 20/01/2018 10:10:49 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblDesembolso generated by hbm2java
 */
@Entity
@Table(name = "tbl_desembolso_arbitrio", schema = "caj")
public class TblDesembolsoArbitrio implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoDesembolsoArbitrio;
	private String tipoCobro;
	private Date fechaCobro;
	private BigDecimal montoSoles;
	private BigDecimal montoDolares;
	private String tipoMoneda;
	private BigDecimal tipoCambio;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String identificacion;
	private Set<TblCobroArbitrio> tblCobrosArbitrios = new HashSet<TblCobroArbitrio>(0);
	private Integer codigoContrato;
	private Integer estadoOperacion;
	private String 	motivoReversion;
	private String nota;
	//Datos de Bancarizado
	private String tipoPago;
	private String tipoBancarizado;
	private String numeroOperacion;
	private Date fechaOperacion;
	
	public TblDesembolsoArbitrio() {
	}

	public TblDesembolsoArbitrio(int codigoDesembolsoArbitrio) {
		this.codigoDesembolsoArbitrio = codigoDesembolsoArbitrio;
	}

	public TblDesembolsoArbitrio(int codigoDesembolsoArbitrio, String tipoCobro, Date fechaCobro, BigDecimal montoSoles,
			BigDecimal montoDolares, String tipoMoneda, BigDecimal tipoCambio, String estado, Integer usuarioCreacion,
			Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion, String ipCreacion,
			String ipModificacion, String identificacion, Set<TblCobroArbitrio> tblCobrosArbitrios,Integer codigoContrato, Integer estadoOperacion, String motivoReversion) {
		this.codigoDesembolsoArbitrio = codigoDesembolsoArbitrio;
		this.tipoCobro = tipoCobro;
		this.fechaCobro = fechaCobro;
		this.montoSoles = montoSoles;
		this.montoDolares = montoDolares;
		this.tipoMoneda = tipoMoneda;
		this.tipoCambio = tipoCambio;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.identificacion = identificacion;
		this.tblCobrosArbitrios = tblCobrosArbitrios;
		this.codigoContrato = codigoContrato;
		this.estadoOperacion = estadoOperacion;
		this.motivoReversion = motivoReversion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_desembolso_arbitrio", unique = true, nullable = false)
	public int getCodigoDesembolsoArbitrio() {
		return this.codigoDesembolsoArbitrio;
	}

	public void setCodigoDesembolsoArbitrio(int codigoDesembolsoArbitrio) {
		this.codigoDesembolsoArbitrio = codigoDesembolsoArbitrio;
	}

	@Column(name = "tipo_cobro", length = 8)
	public String getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(String tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cobro", length = 13)
	public Date getFechaCobro() {
		return this.fechaCobro;
	}

	public void setFechaCobro(Date fechaCobro) {
		this.fechaCobro = fechaCobro;
	}

	@Column(name = "monto_soles", precision = 12)
	public BigDecimal getMontoSoles() {
		return this.montoSoles;
	}

	public void setMontoSoles(BigDecimal montoSoles) {
		this.montoSoles = montoSoles;
	}

	@Column(name = "monto_dolares", precision = 12)
	public BigDecimal getMontoDolares() {
		return this.montoDolares;
	}

	public void setMontoDolares(BigDecimal montoDolares) {
		this.montoDolares = montoDolares;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_cambio", precision = 12)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "identificacion", length = 64)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDesembolsoArbitrio")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblCobroArbitrio> getTblCobrosArbitrios() {
		return this.tblCobrosArbitrios;
	}

	public void setTblCobrosArbitrios(Set<TblCobroArbitrio> tblCobrosArbitrios) {
		this.tblCobrosArbitrios = tblCobrosArbitrios;
	}

	@Column(name = "codigo_contrato")
	public Integer getCodigoContrato() {
		return codigoContrato;
	}

	public void setCodigoContrato(Integer codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

	@Column(name = "estado_operacion")
	public Integer getEstadoOperacion() {
		return estadoOperacion;
	}

	public void setEstadoOperacion(Integer estadoOperacion) {
		this.estadoOperacion = estadoOperacion;
	}

	@Column(name = "motivo_reversion", length = 512)
	public String getMotivoReversion() {
		return motivoReversion;
	}

	public void setMotivoReversion(String motivoReversion) {
		this.motivoReversion = motivoReversion;
	}

	@Column(name = "nota", length = 256)
	public String getNota() {
		return nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "tipo_pago")
	public String getTipoPago() {
		return tipoPago;
	}

	public void setTipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "tipo_bancarizacion")
	public String getTipoBancarizado() {
		return tipoBancarizado;
	}

	public void setTipoBancarizado(String tipoBancarizado) {
		this.tipoBancarizado = tipoBancarizado;
	}

	@Column(name = "numero_operacion")
	public String getNumeroOperacion() {
		return numeroOperacion;
	}

	public void setNumeroOperacion(String numeroOperacion) {
		this.numeroOperacion = numeroOperacion;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_operacion")
	public Date getFechaOperacion() {
		return fechaOperacion;
	}

	public void setFechaOperacion(Date fechaOperacion) {
		this.fechaOperacion = fechaOperacion;
	}

}
