package com.pe.lima.sg.entity.caja;
// Generated 26/11/2017 05:22:50 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TblSunatDetalle generated by hbm2java
 */
@Entity
@Table(name = "tbl_sunat_detalle", schema = "caj")
public class TblSunatDetalle implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoDetalle;
	private TblSunatCabecera tblSunatCabecera;
	private String codigoUnidad;
	private String cantidad;
	private String codigoProducto;
	private String codigoProductoSunat;
	private String descripcion;
	private String valorUnitario;
	private String descuento;
	private String montoIgv;
	private String afectacionIgv;
	private String montoIsc;
	private String tipoIsc;
	private String precioVentaUnitario;
	private String valorVentaItem;
	private String nombreArchivo;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblSunatDetalle() {
	}

	public TblSunatDetalle(int codigoDetalle, TblSunatCabecera tblSunatCabecera) {
		this.codigoDetalle = codigoDetalle;
		this.tblSunatCabecera = tblSunatCabecera;
	}

	public TblSunatDetalle(int codigoDetalle, TblSunatCabecera tblSunatCabecera, String codigoUnidad, String cantidad,
			String codigoProducto, String codigoProductoSunat, String descripcion, String valorUnitario,
			String descuento, String montoIgv, String afectacionIgv, String montoIsc, String tipoIsc,
			String precioVentaUnitario, String valorVentaItem, String nombreArchivo, String estado, Date fechaCreacion,
			Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion, String ipCreacion,
			String ipModificacion) {
		this.codigoDetalle = codigoDetalle;
		this.tblSunatCabecera = tblSunatCabecera;
		this.codigoUnidad = codigoUnidad;
		this.cantidad = cantidad;
		this.codigoProducto = codigoProducto;
		this.codigoProductoSunat = codigoProductoSunat;
		this.descripcion = descripcion;
		this.valorUnitario = valorUnitario;
		this.descuento = descuento;
		this.montoIgv = montoIgv;
		this.afectacionIgv = afectacionIgv;
		this.montoIsc = montoIsc;
		this.tipoIsc = tipoIsc;
		this.precioVentaUnitario = precioVentaUnitario;
		this.valorVentaItem = valorVentaItem;
		this.nombreArchivo = nombreArchivo;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_detalle", unique = true, nullable = false)
	public int getCodigoDetalle() {
		return this.codigoDetalle;
	}

	public void setCodigoDetalle(int codigoDetalle) {
		this.codigoDetalle = codigoDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cabecera", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblSunatCabecera getTblSunatCabecera() {
		return this.tblSunatCabecera;
	}

	public void setTblSunatCabecera(TblSunatCabecera tblSunatCabecera) {
		this.tblSunatCabecera = tblSunatCabecera;
	}

	@Column(name = "codigo_unidad", length = 3)
	public String getCodigoUnidad() {
		return this.codigoUnidad;
	}

	public void setCodigoUnidad(String codigoUnidad) {
		this.codigoUnidad = codigoUnidad;
	}

	@Column(name = "cantidad", length = 23)
	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "codigo_producto", length = 30)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "codigo_producto_sunat", length = 20)
	public String getCodigoProductoSunat() {
		return this.codigoProductoSunat;
	}

	public void setCodigoProductoSunat(String codigoProductoSunat) {
		this.codigoProductoSunat = codigoProductoSunat;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor_unitario", length = 23)
	public String getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(String valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Column(name = "descuento", length = 15)
	public String getDescuento() {
		return this.descuento;
	}

	public void setDescuento(String descuento) {
		this.descuento = descuento;
	}

	@Column(name = "monto_igv", length = 15)
	public String getMontoIgv() {
		return this.montoIgv;
	}

	public void setMontoIgv(String montoIgv) {
		this.montoIgv = montoIgv;
	}

	@Column(name = "afectacion_igv", length = 2)
	public String getAfectacionIgv() {
		return this.afectacionIgv;
	}

	public void setAfectacionIgv(String afectacionIgv) {
		this.afectacionIgv = afectacionIgv;
	}

	@Column(name = "monto_isc", length = 15)
	public String getMontoIsc() {
		return this.montoIsc;
	}

	public void setMontoIsc(String montoIsc) {
		this.montoIsc = montoIsc;
	}

	@Column(name = "tipo_isc", length = 2)
	public String getTipoIsc() {
		return this.tipoIsc;
	}

	public void setTipoIsc(String tipoIsc) {
		this.tipoIsc = tipoIsc;
	}

	@Column(name = "precio_venta_unitario", length = 23)
	public String getPrecioVentaUnitario() {
		return this.precioVentaUnitario;
	}

	public void setPrecioVentaUnitario(String precioVentaUnitario) {
		this.precioVentaUnitario = precioVentaUnitario;
	}

	@Column(name = "valor_venta_item", length = 15)
	public String getValorVentaItem() {
		return this.valorVentaItem;
	}

	public void setValorVentaItem(String valorVentaItem) {
		this.valorVentaItem = valorVentaItem;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

}
