package com.pe.lima.sg.entity.caja;
// Generated 26/11/2017 05:22:50 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblSunatCabecera generated by hbm2java
 */
@Entity
@Table(name = "tbl_sunat_cabecera", schema = "caj")
public class TblSunatCabecera implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoCabecera;
	private TblCxcDocumento tblCxcDocumento;
	private String tipoOperacion;
	private String fechaEmision;
	private Integer domicilioFiscal;
	private String tipoDocumentoUsuario;
	private String numeroDocumento;
	private String razonSocial;
	private String tipoMoneda;
	private BigDecimal sumaDescuento;
	private BigDecimal sumaCargo;
	private BigDecimal totalDescuento;
	private BigDecimal operacionGravada;
	private BigDecimal operacionInafecta;
	private BigDecimal operacionExonerada;
	private BigDecimal montoIgv;
	private BigDecimal montoIsc;
	private BigDecimal otrosTributos;
	private BigDecimal importeTotal;
	private String nombreArchivo;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Integer codigoReferencia;
	private String tipoReferencia;
	private Set<TblSunatDetalle> tblSunatDetalles = new HashSet<TblSunatDetalle>(0);

	public TblSunatCabecera() {
	}

	public TblSunatCabecera(int codigoCabecera, TblCxcDocumento tblCxcDocumento) {
		this.codigoCabecera = codigoCabecera;
		this.tblCxcDocumento = tblCxcDocumento;
	}

	public TblSunatCabecera(int codigoCabecera, TblCxcDocumento tblCxcDocumento, String tipoOperacion,
			String fechaEmision, Integer domicilioFiscal, String tipoDocumentoUsuario, String numeroDocumento,
			String razonSocial, String tipoMoneda, BigDecimal sumaDescuento, BigDecimal sumaCargo,
			BigDecimal totalDescuento, BigDecimal operacionGravada, BigDecimal operacionInafecta,
			BigDecimal operacionExonerada, BigDecimal montoIgv, BigDecimal montoIsc, BigDecimal otrosTributos,
			BigDecimal importeTotal, String nombreArchivo, String estado, Date fechaCreacion, Date fechaModificacion,
			Integer usuarioCreacion, Integer usuarioModificacion, String ipCreacion, String ipModificacion,
			Integer codigoReferencia, String tipoReferencia, Set<TblSunatDetalle> tblSunatDetalles) {
		this.codigoCabecera = codigoCabecera;
		this.tblCxcDocumento = tblCxcDocumento;
		this.tipoOperacion = tipoOperacion;
		this.fechaEmision = fechaEmision;
		this.domicilioFiscal = domicilioFiscal;
		this.tipoDocumentoUsuario = tipoDocumentoUsuario;
		this.numeroDocumento = numeroDocumento;
		this.razonSocial = razonSocial;
		this.tipoMoneda = tipoMoneda;
		this.sumaDescuento = sumaDescuento;
		this.sumaCargo = sumaCargo;
		this.totalDescuento = totalDescuento;
		this.operacionGravada = operacionGravada;
		this.operacionInafecta = operacionInafecta;
		this.operacionExonerada = operacionExonerada;
		this.montoIgv = montoIgv;
		this.montoIsc = montoIsc;
		this.otrosTributos = otrosTributos;
		this.importeTotal = importeTotal;
		this.nombreArchivo = nombreArchivo;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoReferencia = codigoReferencia;
		this.tipoReferencia = tipoReferencia;
		this.tblSunatDetalles = tblSunatDetalles;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_cabecera", unique = true, nullable = false)
	public int getCodigoCabecera() {
		return this.codigoCabecera;
	}

	public void setCodigoCabecera(int codigoCabecera) {
		this.codigoCabecera = codigoCabecera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cxc_doc", nullable = false)
	public TblCxcDocumento getTblCxcDocumento() {
		return this.tblCxcDocumento;
	}

	public void setTblCxcDocumento(TblCxcDocumento tblCxcDocumento) {
		this.tblCxcDocumento = tblCxcDocumento;
	}

	@Column(name = "tipo_operacion")
	public String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	@Column(name = "fecha_emision", length = 10)
	public String getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(String fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "domicilio_fiscal")
	public Integer getDomicilioFiscal() {
		return this.domicilioFiscal;
	}

	public void setDomicilioFiscal(Integer domicilioFiscal) {
		this.domicilioFiscal = domicilioFiscal;
	}

	@Column(name = "tipo_documento_usuario", length = 1)
	public String getTipoDocumentoUsuario() {
		return this.tipoDocumentoUsuario;
	}

	public void setTipoDocumentoUsuario(String tipoDocumentoUsuario) {
		this.tipoDocumentoUsuario = tipoDocumentoUsuario;
	}

	@Column(name = "numero_documento", length = 15)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "razon_social", length = 100)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "tipo_moneda", length = 3)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "suma_descuento", precision = 12)
	public BigDecimal getSumaDescuento() {
		return this.sumaDescuento;
	}

	public void setSumaDescuento(BigDecimal sumaDescuento) {
		this.sumaDescuento = sumaDescuento;
	}

	@Column(name = "suma_cargo", precision = 12)
	public BigDecimal getSumaCargo() {
		return this.sumaCargo;
	}

	public void setSumaCargo(BigDecimal sumaCargo) {
		this.sumaCargo = sumaCargo;
	}

	@Column(name = "total_descuento", precision = 12)
	public BigDecimal getTotalDescuento() {
		return this.totalDescuento;
	}

	public void setTotalDescuento(BigDecimal totalDescuento) {
		this.totalDescuento = totalDescuento;
	}

	@Column(name = "operacion_gravada", precision = 12)
	public BigDecimal getOperacionGravada() {
		return this.operacionGravada;
	}

	public void setOperacionGravada(BigDecimal operacionGravada) {
		this.operacionGravada = operacionGravada;
	}

	@Column(name = "operacion_inafecta", precision = 12)
	public BigDecimal getOperacionInafecta() {
		return this.operacionInafecta;
	}

	public void setOperacionInafecta(BigDecimal operacionInafecta) {
		this.operacionInafecta = operacionInafecta;
	}

	@Column(name = "operacion_exonerada", precision = 12)
	public BigDecimal getOperacionExonerada() {
		return this.operacionExonerada;
	}

	public void setOperacionExonerada(BigDecimal operacionExonerada) {
		this.operacionExonerada = operacionExonerada;
	}

	@Column(name = "monto_igv", precision = 12)
	public BigDecimal getMontoIgv() {
		return this.montoIgv;
	}

	public void setMontoIgv(BigDecimal montoIgv) {
		this.montoIgv = montoIgv;
	}

	@Column(name = "monto_isc", precision = 12)
	public BigDecimal getMontoIsc() {
		return this.montoIsc;
	}

	public void setMontoIsc(BigDecimal montoIsc) {
		this.montoIsc = montoIsc;
	}

	@Column(name = "otros_tributos", precision = 12)
	public BigDecimal getOtrosTributos() {
		return this.otrosTributos;
	}

	public void setOtrosTributos(BigDecimal otrosTributos) {
		this.otrosTributos = otrosTributos;
	}

	@Column(name = "importe_total", precision = 12)
	public BigDecimal getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(BigDecimal importeTotal) {
		this.importeTotal = importeTotal;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "codigo_referencia")
	public Integer getCodigoReferencia() {
		return this.codigoReferencia;
	}

	public void setCodigoReferencia(Integer codigoReferencia) {
		this.codigoReferencia = codigoReferencia;
	}

	@Column(name = "tipo_referencia", length = 8)
	public String getTipoReferencia() {
		return this.tipoReferencia;
	}

	public void setTipoReferencia(String tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblSunatCabecera")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblSunatDetalle> getTblSunatDetalles() {
		return this.tblSunatDetalles;
	}

	public void setTblSunatDetalles(Set<TblSunatDetalle> tblSunatDetalles) {
		this.tblSunatDetalles = tblSunatDetalles;
	}

}
