package com.pe.lima.sg.entity.cliente;
// Generated 11/10/2017 10:08:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TblAdelanto generated by hbm2java
 */
@Entity
@Table(name = "tbl_adelanto", schema = "caj")
public class TblAdelanto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoAdelanto;
	private TblContrato tblContrato;
	private String tipoRubro;
	private Date fechaAdelanto;
	private BigDecimal montoSoles;
	private BigDecimal montoDolares;
	private String tipoMoneda;
	private BigDecimal tipoCambio;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private int codigoCxcDoc;
	private String flagCobro;
	private Integer codigoDesembolso;
	private BigDecimal montoSolesConsumido;
	private BigDecimal montoDolaresConsumido;

	public TblAdelanto() {
	}

	public TblAdelanto(int codigoAdelanto, TblContrato tblContrato, int codigoCxcDoc) {
		this.codigoAdelanto = codigoAdelanto;
		this.tblContrato = tblContrato;
		this.codigoCxcDoc = codigoCxcDoc;
	}

	public TblAdelanto(int codigoAdelanto, TblContrato tblContrato, String tipoRubro, Date fechaAdelanto,
			BigDecimal montoSoles, BigDecimal montoDolares, String tipoMoneda, BigDecimal tipoCambio, String estado,
			Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion, int codigoCxcDoc, String flagCobro, Integer codigoDesembolso, BigDecimal montoSolesConsumido, BigDecimal montoDolaresConsumido) {
		this.codigoAdelanto = codigoAdelanto;
		this.tblContrato = tblContrato;
		this.tipoRubro = tipoRubro;
		this.fechaAdelanto = fechaAdelanto;
		this.montoSoles = montoSoles;
		this.montoDolares = montoDolares;
		this.tipoMoneda = tipoMoneda;
		this.tipoCambio = tipoCambio;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoCxcDoc = codigoCxcDoc;
		this.flagCobro = flagCobro;
		this.codigoDesembolso = codigoDesembolso;
		this.montoSolesConsumido = montoSolesConsumido;
		this.montoDolaresConsumido = montoDolaresConsumido;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_adelanto", unique = true, nullable = false)
	public int getCodigoAdelanto() {
		return this.codigoAdelanto;
	}

	public void setCodigoAdelanto(int codigoAdelanto) {
		this.codigoAdelanto = codigoAdelanto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_contrato", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblContrato getTblContrato() {
		return this.tblContrato;
	}

	public void setTblContrato(TblContrato tblContrato) {
		this.tblContrato = tblContrato;
	}

	@Column(name = "tipo_rubro", length = 8)
	public String getTipoRubro() {
		return this.tipoRubro;
	}

	public void setTipoRubro(String tipoRubro) {
		this.tipoRubro = tipoRubro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_adelanto", length = 13)
	public Date getFechaAdelanto() {
		return this.fechaAdelanto;
	}

	public void setFechaAdelanto(Date fechaAdelanto) {
		this.fechaAdelanto = fechaAdelanto;
	}

	@Column(name = "monto_soles", precision = 12)
	public BigDecimal getMontoSoles() {
		return this.montoSoles;
	}

	public void setMontoSoles(BigDecimal montoSoles) {
		this.montoSoles = montoSoles;
	}

	@Column(name = "monto_dolares", precision = 12)
	public BigDecimal getMontoDolares() {
		return this.montoDolares;
	}

	public void setMontoDolares(BigDecimal montoDolares) {
		this.montoDolares = montoDolares;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_cambio", precision = 12)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "codigo_cxc_doc", nullable = false)
	public int getCodigoCxcDoc() {
		return this.codigoCxcDoc;
	}

	public void setCodigoCxcDoc(int codigoCxcDoc) {
		this.codigoCxcDoc = codigoCxcDoc;
	}

	@Column(name = "flag_cobro", length = 1)
	public String getFlagCobro() {
		return this.flagCobro;
	}

	public void setFlagCobro(String flagCobro) {
		this.flagCobro = flagCobro;
	}

	@Column(name = "codigo_desembolso")
	public Integer getCodigoDesembolso() {
		return this.codigoDesembolso;
	}

	public void setCodigoDesembolso(Integer codigoDesembolso) {
		this.codigoDesembolso = codigoDesembolso;
	}

	@Column(name = "monto_soles_consumido", precision = 12)
	public BigDecimal getMontoSolesConsumido() {
		return montoSolesConsumido;
	}

	public void setMontoSolesConsumido(BigDecimal montoSolesConsumido) {
		this.montoSolesConsumido = montoSolesConsumido;
	}

	@Column(name = "monto_dolares_consumido", precision = 12)
	public BigDecimal getMontoDolaresConsumido() {
		return montoDolaresConsumido;
	}

	public void setMontoDolaresConsumido(BigDecimal montoDolaresConsumido) {
		this.montoDolaresConsumido = montoDolaresConsumido;
	}

}
