package com.pe.lima.sg.entity.cliente;
// Generated 11/10/2017 10:08:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.entity.mantenimiento.TblTipoServicio;

/**
 * TblContratoServicio generated by hbm2java
 */
@Entity
@Table(name = "tbl_contrato_servicio", schema = "cli")
public class TblContratoServicio implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoServicio;
	private TblContrato tblContrato;
	private TblTipoServicio tblTipoServicio;
	private BigDecimal monto;
	private BigDecimal primerCobroServicio;
	private String tipoMonedaServicio;
	private String tipoDocumentoServicio;
	private BigDecimal totalAcumulado;
	private BigDecimal totalCobrado;
	private BigDecimal totalSaldo;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblContratoServicio() {
		this.tblTipoServicio = new TblTipoServicio();
	}

	public TblContratoServicio(int codigoServicio, TblContrato tblContrato, TblTipoServicio tblTipoServicio) {
		this.codigoServicio = codigoServicio;
		this.tblContrato = tblContrato;
		this.tblTipoServicio = tblTipoServicio;
	}

	public TblContratoServicio(int codigoServicio, TblContrato tblContrato, TblTipoServicio tblTipoServicio,
			BigDecimal monto,BigDecimal primerCobroServicio, String tipoMonedaServicio, String tipoDocumentoServicio, BigDecimal totalAcumulado,
			BigDecimal totalCobrado, BigDecimal totalSaldo, String estado, Integer usuarioCreacion,
			Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion, String ipCreacion,
			String ipModificacion) {
		this.codigoServicio = codigoServicio;
		this.tblContrato = tblContrato;
		this.tblTipoServicio = tblTipoServicio;
		this.monto = monto;
		this.primerCobroServicio = primerCobroServicio;
		this.tipoMonedaServicio = tipoMonedaServicio;
		this.tipoDocumentoServicio = tipoDocumentoServicio;
		this.totalAcumulado = totalAcumulado;
		this.totalCobrado = totalCobrado;
		this.totalSaldo = totalSaldo;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_servicio", unique = true, nullable = false)
	public int getCodigoServicio() {
		return this.codigoServicio;
	}

	public void setCodigoServicio(int codigoServicio) {
		this.codigoServicio = codigoServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_contrato", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblContrato getTblContrato() {
		return this.tblContrato;
	}

	public void setTblContrato(TblContrato tblContrato) {
		this.tblContrato = tblContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_servicio", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblTipoServicio getTblTipoServicio() {
		return this.tblTipoServicio;
	}

	public void setTblTipoServicio(TblTipoServicio tblTipoServicio) {
		this.tblTipoServicio = tblTipoServicio;
	}

	@Column(name = "monto", precision = 12)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "tipo_moneda_servicio", length = 2)
	public String getTipoMonedaServicio() {
		return this.tipoMonedaServicio;
	}

	public void setTipoMonedaServicio(String tipoMonedaServicio) {
		this.tipoMonedaServicio = tipoMonedaServicio;
	}

	@Column(name = "tipo_documento_servicio", length = 8)
	public String getTipoDocumentoServicio() {
		return this.tipoDocumentoServicio;
	}

	public void setTipoDocumentoServicio(String tipoDocumentoServicio) {
		this.tipoDocumentoServicio = tipoDocumentoServicio;
	}

	@Column(name = "total_acumulado", precision = 12)
	public BigDecimal getTotalAcumulado() {
		return this.totalAcumulado;
	}

	public void setTotalAcumulado(BigDecimal totalAcumulado) {
		this.totalAcumulado = totalAcumulado;
	}

	@Column(name = "total_cobrado", precision = 12)
	public BigDecimal getTotalCobrado() {
		return this.totalCobrado;
	}

	public void setTotalCobrado(BigDecimal totalCobrado) {
		this.totalCobrado = totalCobrado;
	}

	@Column(name = "total_saldo", precision = 12)
	public BigDecimal getTotalSaldo() {
		return this.totalSaldo;
	}

	public void setTotalSaldo(BigDecimal totalSaldo) {
		this.totalSaldo = totalSaldo;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "primer_cobro", precision = 12)
	public BigDecimal getPrimerCobroServicio() {
		return primerCobroServicio;
	}

	public void setPrimerCobroServicio(BigDecimal primerCobroServicio) {
		this.primerCobroServicio = primerCobroServicio;
	}

}
