package com.pe.lima.sg.entity.cliente;
// Generated 11/10/2017 10:08:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.pe.lima.sg.entity.mantenimiento.TblPersona;
import com.pe.lima.sg.entity.mantenimiento.TblTienda;

/**
 * TblContrato generated by hbm2java
 */
@Entity
@Table(name = "tbl_contrato", schema = "cli")
public class TblContrato implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoContrato;
	private TblPersona tblPersona;
	private TblTienda tblTienda;
	private String numero;
	private String estadoContrato;
	private Date fechaContrato;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal montoAlquiler;
	private BigDecimal primerCobroAlquiler;
	private String tipoMonedaAlquiler;
	private String tipoCobro;
	private String tipoGarantia;
	private BigDecimal montoGarantia;
	private String tipoMonedaGarantia;
	private String informacionAdicional;
	private String tipoDocumentoGarantia;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Integer codigoPadreContrato;
	private Set<TblAdelanto> tblAdelantos = new HashSet<TblAdelanto>(0);
	private Set<TblContratoServicio> tblContratoServicios = new HashSet<TblContratoServicio>(0);
	private Set<TblContratoCliente> tblContratoClientes = new HashSet<TblContratoCliente>(0);
	private Set<TblContratoPrimerCobro> tblContratoPrimerCobros = new HashSet<TblContratoPrimerCobro>(0);
	private String tipoDocumentoAlquiler;
	private Integer periodoAdelanto;
	private Date fechaFinalizacion;

	public TblContrato() {
	}

	public TblContrato(int codigoContrato, TblPersona tblPersona, TblTienda tblTienda) {
		this.codigoContrato = codigoContrato;
		this.tblPersona = tblPersona;
		this.tblTienda = tblTienda;
	}

	public TblContrato(int codigoContrato, TblPersona tblPersona, TblTienda tblTienda, String numero,
			String estadoContrato, Date fechaContrato, Date fechaInicio, Date fechaFin, BigDecimal montoAlquiler, BigDecimal primerCobroAlquiler,
			String tipoMonedaAlquiler, String tipoCobro, String tipoGarantia, BigDecimal montoGarantia,
			String tipoMonedaGarantia, String informacionAdicional, String tipoDocumentoGarantia, String estado,
			Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion, Integer codigoPadreContrato, Set<TblContratoPrimerCobro> tblContratoPrimerCobros, Set<TblAdelanto> tblAdelantos,
			Set<TblContratoServicio> tblContratoServicios,Set<TblContratoCliente> tblContratoClientes,
			String tipoDocumentoAlquiler, Integer periodoAdelanto, Date fechaFinalizacion) {
		this.codigoContrato = codigoContrato;
		this.tblPersona = tblPersona;
		this.tblTienda = tblTienda;
		this.numero = numero;
		this.estadoContrato = estadoContrato;
		this.fechaContrato = fechaContrato;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.montoAlquiler = montoAlquiler;
		this.primerCobroAlquiler = primerCobroAlquiler;
		this.tipoMonedaAlquiler = tipoMonedaAlquiler;
		this.tipoCobro = tipoCobro;
		this.tipoGarantia = tipoGarantia;
		this.montoGarantia = montoGarantia;
		this.tipoMonedaGarantia = tipoMonedaGarantia;
		this.informacionAdicional = informacionAdicional;
		this.tipoDocumentoGarantia = tipoDocumentoGarantia;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoPadreContrato = codigoPadreContrato;
		this.tblAdelantos = tblAdelantos;
		this.tblContratoServicios = tblContratoServicios;
		this.tblContratoClientes = tblContratoClientes;
		this.tblContratoPrimerCobros = tblContratoPrimerCobros;
		this.tipoDocumentoAlquiler = tipoDocumentoAlquiler;
		this.periodoAdelanto = periodoAdelanto;
		this.fechaFinalizacion = fechaFinalizacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_contrato", unique = true, nullable = false)
	public int getCodigoContrato() {
		return this.codigoContrato;
	}

	public void setCodigoContrato(int codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_persona", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblPersona getTblPersona() {
		return this.tblPersona;
	}

	public void setTblPersona(TblPersona tblPersona) {
		this.tblPersona = tblPersona;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_tienda", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblTienda getTblTienda() {
		return this.tblTienda;
	}

	public void setTblTienda(TblTienda tblTienda) {
		this.tblTienda = tblTienda;
	}

	@Column(name = "numero", length = 16)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "estado_contrato", length = 8)
	public String getEstadoContrato() {
		return this.estadoContrato;
	}

	public void setEstadoContrato(String estadoContrato) {
		this.estadoContrato = estadoContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_contrato", length = 13)
	public Date getFechaContrato() {
		return this.fechaContrato;
	}

	public void setFechaContrato(Date fechaContrato) {
		this.fechaContrato = fechaContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "monto_alquiler", precision = 12)
	public BigDecimal getMontoAlquiler() {
		return this.montoAlquiler;
	}

	public void setMontoAlquiler(BigDecimal montoAlquiler) {
		this.montoAlquiler = montoAlquiler;
	}

	@Column(name = "tipo_moneda_alquiler", length = 2)
	public String getTipoMonedaAlquiler() {
		return this.tipoMonedaAlquiler;
	}

	public void setTipoMonedaAlquiler(String tipoMonedaAlquiler) {
		this.tipoMonedaAlquiler = tipoMonedaAlquiler;
	}

	@Column(name = "tipo_cobro", length = 8)
	public String getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(String tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Column(name = "tipo_garantia", length = 8)
	public String getTipoGarantia() {
		return this.tipoGarantia;
	}

	public void setTipoGarantia(String tipoGarantia) {
		this.tipoGarantia = tipoGarantia;
	}

	@Column(name = "monto_garantia", precision = 12)
	public BigDecimal getMontoGarantia() {
		return this.montoGarantia;
	}

	public void setMontoGarantia(BigDecimal montoGarantia) {
		this.montoGarantia = montoGarantia;
	}

	@Column(name = "tipo_moneda_garantia", length = 2)
	public String getTipoMonedaGarantia() {
		return this.tipoMonedaGarantia;
	}

	public void setTipoMonedaGarantia(String tipoMonedaGarantia) {
		this.tipoMonedaGarantia = tipoMonedaGarantia;
	}

	@Column(name = "informacion_adicional", length = 512)
	public String getInformacionAdicional() {
		return this.informacionAdicional;
	}

	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}

	@Column(name = "tipo_documento_garantia", length = 8)
	public String getTipoDocumentoGarantia() {
		return this.tipoDocumentoGarantia;
	}

	public void setTipoDocumentoGarantia(String tipoDocumentoGarantia) {
		this.tipoDocumentoGarantia = tipoDocumentoGarantia;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "codigo_padre_contrato")
	public Integer getCodigoPadreContrato() {
		return this.codigoPadreContrato;
	}

	public void setCodigoPadreContrato(Integer codigoPadreContrato) {
		this.codigoPadreContrato = codigoPadreContrato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblContrato")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblAdelanto> getTblAdelantos() {
		return this.tblAdelantos;
	}

	public void setTblAdelantos(Set<TblAdelanto> tblAdelantos) {
		this.tblAdelantos = tblAdelantos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblContrato")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblContratoServicio> getTblContratoServicios() {
		return this.tblContratoServicios;
	}

	public void setTblContratoServicios(Set<TblContratoServicio> tblContratoServicios) {
		this.tblContratoServicios = tblContratoServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblContrato")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblContratoCliente> getTblContratoClientes() {
		return this.tblContratoClientes;
	}

	public void setTblContratoClientes(Set<TblContratoCliente> tblContratoClientes) {
		this.tblContratoClientes = tblContratoClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblContrato")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblContratoPrimerCobro> getTblContratoPrimerCobros() {
		return this.tblContratoPrimerCobros;
	}

	public void setTblContratoPrimerCobros(Set<TblContratoPrimerCobro> tblContratoPrimerCobros) {
		this.tblContratoPrimerCobros = tblContratoPrimerCobros;
	}

	@Column(name = "tipo_documento_alquiler", length = 8)
	public String getTipoDocumentoAlquiler() {
		return tipoDocumentoAlquiler;
	}

	public void setTipoDocumentoAlquiler(String tipoDocumentoAlquiler) {
		this.tipoDocumentoAlquiler = tipoDocumentoAlquiler;
	}

	@Column(name = "periodo_adelanto")
	public Integer getPeriodoAdelanto() {
		return periodoAdelanto;
	}

	public void setPeriodoAdelanto(Integer periodoAdelanto) {
		this.periodoAdelanto = periodoAdelanto;
	}

	@Column(name = "primer_cobro", precision = 12)
	public BigDecimal getPrimerCobroAlquiler() {
		return primerCobroAlquiler;
	}

	public void setPrimerCobroAlquiler(BigDecimal primerCobroAlquiler) {
		this.primerCobroAlquiler = primerCobroAlquiler;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_finalizacion", length = 13)
	public Date getFechaFinalizacion() {
		return fechaFinalizacion;
	}

	public void setFechaFinalizacion(Date fechaFinalizacion) {
		this.fechaFinalizacion = fechaFinalizacion;
	}

}
