package com.pe.lima.sg.entity.cliente;
// Generated 14/10/2017 10:22:12 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.entity.mantenimiento.TblTipoServicio;

/**
 * TblContratoPrimerCobro generated by hbm2java
 */
@Entity
@Table(name = "tbl_contrato_primer_cobro", schema = "cli")
public class TblContratoPrimerCobro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoPrimero;
	private TblContrato tblContrato;
	private TblTipoServicio tblTipoServicio;
	private BigDecimal montoCobro;
	private String tipoMoneda;
	private String tipoDocumento;
	private String numeroDocumento;
	private Date fechaCobro;
	private String observacion;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblContratoPrimerCobro() {
	}

	public TblContratoPrimerCobro(int codigoPrimero, TblContrato tblContrato, TblTipoServicio tblTipoServicio) {
		this.codigoPrimero = codigoPrimero;
		this.tblContrato = tblContrato;
		this.tblTipoServicio = tblTipoServicio;
	}

	public TblContratoPrimerCobro(int codigoPrimero, TblContrato tblContrato, TblTipoServicio tblTipoServicio,
			BigDecimal montoCobro, String tipoMoneda, String tipoDocumento, String numeroDocumento, Date fechaCobro,
			String observacion, String estado, Integer usuarioCreacion, Integer usuarioModificacion,
			Date fechaCreacion, Date fechaModificacion, String ipCreacion, String ipModificacion) {
		this.codigoPrimero = codigoPrimero;
		this.tblContrato = tblContrato;
		this.tblTipoServicio = tblTipoServicio;
		this.montoCobro = montoCobro;
		this.tipoMoneda = tipoMoneda;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.fechaCobro = fechaCobro;
		this.observacion = observacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_primero", unique = true, nullable = false)
	public int getCodigoPrimero() {
		return this.codigoPrimero;
	}

	public void setCodigoPrimero(int codigoPrimero) {
		this.codigoPrimero = codigoPrimero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_contrato", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblContrato getTblContrato() {
		return this.tblContrato;
	}

	public void setTblContrato(TblContrato tblContrato) {
		this.tblContrato = tblContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_servicio", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblTipoServicio getTblTipoServicio() {
		return this.tblTipoServicio;
	}

	public void setTblTipoServicio(TblTipoServicio tblTipoServicio) {
		this.tblTipoServicio = tblTipoServicio;
	}

	@Column(name = "monto_cobro", precision = 12)
	public BigDecimal getMontoCobro() {
		return this.montoCobro;
	}

	public void setMontoCobro(BigDecimal montoCobro) {
		this.montoCobro = montoCobro;
	}

	@Column(name = "tipo_moneda", length = 2)
	public String getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(String tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "tipo_documento", length = 8)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero_documento", length = 16)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cobro", length = 13)
	public Date getFechaCobro() {
		return this.fechaCobro;
	}

	public void setFechaCobro(Date fechaCobro) {
		this.fechaCobro = fechaCobro;
	}

	@Column(name = "observacion", length = 512)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

}
