package com.pe.lima.sg.entity.cliente;
// Generated 11/10/2017 10:08:10 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.entity.mantenimiento.TblTienda;

/**
 * TblLuzxtienda generated by hbm2java
 */
@Entity
@Table(name = "tbl_luzxtienda", schema = "cli")
public class TblLuzxtienda implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoLuzxtienda;
	private TblLuz tblLuz;
	private TblTienda tblTienda;
	private BigDecimal montoGenerado;
	private BigDecimal montoContrato;
	private BigDecimal valorCobrado;
	private BigDecimal saldo;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private int codigoContrato;
	//Calculo del valor restante
	private BigDecimal montoCalculado;
	private BigDecimal montoSinTienda;
	public TblLuzxtienda() {
		this.montoGenerado = new BigDecimal("0");
		this.montoContrato = new BigDecimal("0");
		this.valorCobrado = new BigDecimal("0");
		this.saldo = new BigDecimal("0");
	}

	public TblLuzxtienda(int codigoLuzxtienda, TblLuz tblLuz, TblTienda tblTienda, int codigoContrato) {
		this.codigoLuzxtienda = codigoLuzxtienda;
		this.tblLuz = tblLuz;
		this.tblTienda = tblTienda;
		this.codigoContrato = codigoContrato;
	}

	public TblLuzxtienda(int codigoLuzxtienda, TblLuz tblLuz, TblTienda tblTienda, BigDecimal montoGenerado,
			BigDecimal montoContrato, BigDecimal valorCobrado, BigDecimal saldo, Date fechaInicio, Date fechaFin,
			String estado, Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion,
			Date fechaModificacion, String ipCreacion, String ipModificacion, int codigoContrato) {
		this.codigoLuzxtienda = codigoLuzxtienda;
		this.tblLuz = tblLuz;
		this.tblTienda = tblTienda;
		this.montoGenerado = montoGenerado;
		this.montoContrato = montoContrato;
		this.valorCobrado = valorCobrado;
		this.saldo = saldo;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoContrato = codigoContrato;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_luzxtienda", unique = true, nullable = false)
	public int getCodigoLuzxtienda() {
		return this.codigoLuzxtienda;
	}

	public void setCodigoLuzxtienda(int codigoLuzxtienda) {
		this.codigoLuzxtienda = codigoLuzxtienda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_luz", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblLuz getTblLuz() {
		return this.tblLuz;
	}

	public void setTblLuz(TblLuz tblLuz) {
		this.tblLuz = tblLuz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tienda", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblTienda getTblTienda() {
		return this.tblTienda;
	}

	public void setTblTienda(TblTienda tblTienda) {
		this.tblTienda = tblTienda;
	}

	@Column(name = "monto_generado", precision = 12)
	public BigDecimal getMontoGenerado() {
		return this.montoGenerado;
	}

	public void setMontoGenerado(BigDecimal montoGenerado) {
		this.montoGenerado = montoGenerado;
	}

	@Column(name = "monto_contrato", precision = 12)
	public BigDecimal getMontoContrato() {
		return this.montoContrato;
	}

	public void setMontoContrato(BigDecimal montoContrato) {
		this.montoContrato = montoContrato;
	}

	@Column(name = "valor_cobrado", precision = 12)
	public BigDecimal getValorCobrado() {
		return this.valorCobrado;
	}

	public void setValorCobrado(BigDecimal valorCobrado) {
		this.valorCobrado = valorCobrado;
	}

	@Column(name = "saldo", precision = 12)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}
	@Column(name = "codigo_contrato", nullable = false)
	public int getCodigoContrato() {
		return codigoContrato;
	}

	public void setCodigoContrato(int codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

	@Transient
	public BigDecimal getMontoCalculado() {
		return montoCalculado;
	}

	public void setMontoCalculado(BigDecimal montoCalculado) {
		this.montoCalculado = montoCalculado;
	}

	@Transient
	public BigDecimal getMontoSinTienda() {
		return montoSinTienda;
	}

	public void setMontoSinTienda(BigDecimal montoSinTienda) {
		this.montoSinTienda = montoSinTienda;
	}

}
