package com.pe.lima.sg.entity.mantenimiento;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPersona generated by hbm2java
 */
@Entity
@Table(name = "tbl_persona", schema = "mae")
public class TblPersona implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoPersona;
	private String tipoPersona;
	private String nombre;
	private String paterno;
	private String materno;
	private String estadoCivil;
	private String numeroDni;
	private String numeroRuc;
	private String razonSocial;
	private String tipoCliente;
	private String tipoProveedor;
	private String telefono1;
	private String telefono2;
	private String celular1;
	private String celular2;
	private String correoElectronico;
	private String direccionEmpresa;
	private String direccionCasa;
	private String observacion;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String departamento;
	private String provincia;
	private String distrito;
	
	public TblPersona() {
	}

	public TblPersona(int codigoPersona) {
		this.codigoPersona = codigoPersona;
	}

	public TblPersona(int codigoPersona, String tipoPersona, String nombre, String paterno, String materno,
			String estadoCivil, String numeroDni, String numeroRuc, String razonSocial, String tipoCliente,
			String tipoProveedor, String telefono1, String telefono2, String celular1, String celular2,
			String correoElectronico, String direccionEmpresa, String direccionCasa, String observacion,
			String estado, Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion,
			Date fechaModificacion, String ipCreacion, String ipModificacion) {
		this.codigoPersona = codigoPersona;
		this.tipoPersona = tipoPersona;
		this.nombre = nombre;
		this.paterno = paterno;
		this.materno = materno;
		this.estadoCivil = estadoCivil;
		this.numeroDni = numeroDni;
		this.numeroRuc = numeroRuc;
		this.razonSocial = razonSocial;
		this.tipoCliente = tipoCliente;
		this.tipoProveedor = tipoProveedor;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.celular1 = celular1;
		this.celular2 = celular2;
		this.correoElectronico = correoElectronico;
		this.direccionEmpresa = direccionEmpresa;
		this.direccionCasa = direccionCasa;
		this.observacion = observacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_persona", unique = true, nullable = false)
	public int getCodigoPersona() {
		return this.codigoPersona;
	}

	public void setCodigoPersona(int codigoPersona) {
		this.codigoPersona = codigoPersona;
	}

	@Column(name = "tipo_persona", length = 1)
	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@Column(name = "nombre", length = 64)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "paterno", length = 64)
	public String getPaterno() {
		return this.paterno;
	}

	public void setPaterno(String paterno) {
		this.paterno = paterno;
	}

	@Column(name = "materno", length = 64)
	public String getMaterno() {
		return this.materno;
	}

	public void setMaterno(String materno) {
		this.materno = materno;
	}

	@Column(name = "estado_civil")
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "numero_dni", length = 32)
	public String getNumeroDni() {
		return this.numeroDni;
	}

	public void setNumeroDni(String numeroDni) {
		this.numeroDni = numeroDni;
	}

	@Column(name = "numero_ruc", length = 32)
	public String getNumeroRuc() {
		return this.numeroRuc;
	}

	public void setNumeroRuc(String numeroRuc) {
		this.numeroRuc = numeroRuc;
	}

	@Column(name = "razon_social", length = 128)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "tipo_cliente", length = 1)
	public String getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(String tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	@Column(name = "tipo_proveedor", length = 1)
	public String getTipoProveedor() {
		return this.tipoProveedor;
	}

	public void setTipoProveedor(String tipoProveedor) {
		this.tipoProveedor = tipoProveedor;
	}

	@Column(name = "telefono1", length = 16)
	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "telefono2", length = 16)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "celular1", length = 16)
	public String getCelular1() {
		return this.celular1;
	}

	public void setCelular1(String celular1) {
		this.celular1 = celular1;
	}

	@Column(name = "celular2", length = 16)
	public String getCelular2() {
		return this.celular2;
	}

	public void setCelular2(String celular2) {
		this.celular2 = celular2;
	}

	@Column(name = "correo_electronico", length = 128)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "direccion_empresa", length = 256)
	public String getDireccionEmpresa() {
		return this.direccionEmpresa;
	}

	public void setDireccionEmpresa(String direccionEmpresa) {
		this.direccionEmpresa = direccionEmpresa;
	}

	@Column(name = "direccion_casa", length = 256)
	public String getDireccionCasa() {
		return this.direccionCasa;
	}

	public void setDireccionCasa(String direccionCasa) {
		this.direccionCasa = direccionCasa;
	}

	@Column(name = "observacion", length = 512)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "distrito", length = 8)
	public String getDistrito() {
		return distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "departamento", length = 8)
	public String getDepartamento() {
		return departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "provincia", length = 8)
	public String getProvincia() {
		return provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

}
