package com.pe.lima.sg.entity.mantenimiento;
// Generated 18/09/2017 01:36:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.pe.lima.sg.entity.cliente.TblLuz;

/**
 * TblSuministro generated by hbm2java
 */
@Entity
@Table(name = "tbl_suministro", schema = "mae")
public class TblSuministro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoSuministro;
	private String numero;
	private String observacion;
	private String estadoSuministro;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Set<TblLuz> tblLuzs = new HashSet<TblLuz>(0);
	private Set<TblTienda> tblTiendas = new HashSet<TblTienda>(0);

	public TblSuministro() {
	}

	public TblSuministro(int codigoSuministro) {
		this.codigoSuministro = codigoSuministro;
	}

	public TblSuministro(int codigoSuministro, String numero, String observacion, String estadoSuministro, String estado,
			Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String ipCreacion, String ipModificacion, Set<TblLuz> tblLuzs, Set<TblTienda> tblTiendas) {
		this.codigoSuministro = codigoSuministro;
		this.numero = numero;
		this.observacion = observacion;
		this.estadoSuministro = estadoSuministro;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tblLuzs = tblLuzs;
		this.tblTiendas = tblTiendas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_suministro", unique = true, nullable = false)
	public int getCodigoSuministro() {
		return this.codigoSuministro;
	}

	public void setCodigoSuministro(int codigoSuministro) {
		this.codigoSuministro = codigoSuministro;
	}

	@Column(name = "numero", length = 64)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "observacion", length = 256)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblSuministro")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblTienda> getTblTiendas() {
		return this.tblTiendas;
	}

	public void setTblTiendas(Set<TblTienda> tblTiendas) {
		this.tblTiendas = tblTiendas;
	}
	@Column(name = "estado_suministro", length = 1)
	public String getEstadoSuministro() {
		return estadoSuministro;
	}

	public void setEstadoSuministro(String estadoSuministro) {
		this.estadoSuministro = estadoSuministro;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblSuministro")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblLuz> getTblLuzs() {
		return tblLuzs;
	}

	public void setTblLuzs(Set<TblLuz> tblLuzs) {
		this.tblLuzs = tblLuzs;
	}

}
