package com.pe.lima.sg.entity.mantenimiento;
// Generated 26/11/2017 05:22:50 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblSerie generated by hbm2java
 */
@Entity
@Table(name = "tbl_ubigeo", schema = "mae")
public class TblUbigeo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoUbigeo;
	private String nombre;
	private String codigoInei;
	private String codigoPadreInei;	
	
	public TblUbigeo() {
	}

	public TblUbigeo(int codigoUbigeo) {
		this.codigoUbigeo = codigoUbigeo;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_ubigeo", unique = true, nullable = false)
	public int getCodigoUbigeo() {
		return this.codigoUbigeo;
	}

	public void setCodigoUbigeo(int codigoUbigeo) {
		this.codigoUbigeo = codigoUbigeo;
	}

	@Column(name = "nombre", length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "codigo_inei", length = 8)
	public String getCodigoInei() {
		return this.codigoInei;
	}

	public void setCodigoInei(String codigoInei) {
		this.codigoInei = codigoInei;
	}


	@Column(name = "codigo_padre_inei", length = 8)
	public String getCodigoPadreInei() {
		return this.codigoPadreInei;
	}

	public void setCodigoPadreInei(String codigoPadreInei) {
		this.codigoPadreInei = codigoPadreInei;
	}
}
