package com.pe.lima.sg.facturador.entity;
// Generated 23/12/2017 12:39:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblBandejaFacturador generated by hbm2java
 */
@Entity
@Table(name = "tbl_bandeja_facturador", schema = "ope")
public class TblBandejaFacturador implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoBandeja;
	private TblComprobante tblComprobante;
	private String numeroRuc;
	private String tipoDocumento;
	private String numeroDocumento;
	private String fechaCargue;
	private String fechaGeneracion;
	private String fechaEnvio;
	private String observacion;
	private String nombreArchivo;
	private String situacion;
	private String tipoArchivo;
	private String firmaDigital;
	private Integer estadoOperacion;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;

	public TblBandejaFacturador() {
	}

	public TblBandejaFacturador(int codigoBandeja, TblComprobante tblComprobante) {
		this.codigoBandeja = codigoBandeja;
		this.tblComprobante = tblComprobante;
	}

	public TblBandejaFacturador(int codigoBandeja, TblComprobante tblComprobante, String numeroRuc,
			String tipoDocumento, String numeroDocumento, String fechaCargue, String fechaGeneracion, String fechaEnvio,
			String observacion, String nombreArchivo, String situacion, String tipoArchivo, String firmaDigital,
			Integer estadoOperacion, String estado, Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion,
			Integer usuarioModificacion, String ipCreacion, String ipModificacion) {
		this.codigoBandeja = codigoBandeja;
		this.tblComprobante = tblComprobante;
		this.numeroRuc = numeroRuc;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.fechaCargue = fechaCargue;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaEnvio = fechaEnvio;
		this.observacion = observacion;
		this.nombreArchivo = nombreArchivo;
		this.situacion = situacion;
		this.tipoArchivo = tipoArchivo;
		this.firmaDigital = firmaDigital;
		this.estadoOperacion = estadoOperacion;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_bandeja", unique = true, nullable = false)
	public int getCodigoBandeja() {
		return this.codigoBandeja;
	}

	public void setCodigoBandeja(int codigoBandeja) {
		this.codigoBandeja = codigoBandeja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comprobante", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblComprobante getTblComprobante() {
		return this.tblComprobante;
	}

	public void setTblComprobante(TblComprobante tblComprobante) {
		this.tblComprobante = tblComprobante;
	}

	@Column(name = "numero_ruc", length = 16)
	public String getNumeroRuc() {
		return this.numeroRuc;
	}

	public void setNumeroRuc(String numeroRuc) {
		this.numeroRuc = numeroRuc;
	}

	@Column(name = "tipo_documento", length = 8)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero_documento", length = 64)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "fecha_cargue", length = 32)
	public String getFechaCargue() {
		return this.fechaCargue;
	}

	public void setFechaCargue(String fechaCargue) {
		this.fechaCargue = fechaCargue;
	}

	@Column(name = "fecha_generacion", length = 32)
	public String getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(String fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	@Column(name = "fecha_envio", length = 32)
	public String getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(String fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Column(name = "observacion", length = 256)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "nombre_archivo", length = 256)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "situacion", length = 2)
	public String getSituacion() {
		return this.situacion;
	}

	public void setSituacion(String situacion) {
		this.situacion = situacion;
	}

	@Column(name = "tipo_archivo", length = 8)
	public String getTipoArchivo() {
		return this.tipoArchivo;
	}

	public void setTipoArchivo(String tipoArchivo) {
		this.tipoArchivo = tipoArchivo;
	}

	@Column(name = "firma_digital", length = 512)
	public String getFirmaDigital() {
		return this.firmaDigital;
	}

	public void setFirmaDigital(String firmaDigital) {
		this.firmaDigital = firmaDigital;
	}

	@Column(name = "estado_operacion")
	public Integer getEstadoOperacion() {
		return this.estadoOperacion;
	}

	public void setEstadoOperacion(Integer estadoOperacion) {
		this.estadoOperacion = estadoOperacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}
	public void setAuditoriaCreacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(request.getRemoteAddr());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioCreacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
	
	public void setAuditoriaModificacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(request.getRemoteAddr());
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioModificacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
}
