package com.pe.lima.sg.facturador.entity;
// Generated 17/12/2017 10:06:23 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.facturador.bean.AuditoriaBean;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblDetalleComprobante generated by hbm2java
 */
@Entity
@Table(name = "tbl_detalle_comprobante", schema = "ope")
public class TblDetalleComprobante implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoDetalle;
	private TblComprobante tblComprobante;
	private String descripcion;
	private BigDecimal cantidad			= new BigDecimal("0");	
	private BigDecimal precioUnitario	= new BigDecimal("0");
	private BigDecimal descuento		= new BigDecimal("0");
	private BigDecimal precioTotal		= new BigDecimal("0");
	private BigDecimal precioFinal		= new BigDecimal("0");
	private String unidadMedida;
	private BigDecimal valorReferencia	= new BigDecimal("0");
	private String tipoAfectacion;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String moneda;
	private String codigoProducto;
	private String codigoProductoSunat;
	private BigDecimal sumTributosItem;
	private String tribCodTipoTributoIgv;
	private BigDecimal tribMontoIgv;
	private BigDecimal tribBaseImponibleIgv;
	private String tribNombreTributo;
	private String tribCodTipoTributo;
	private String tribAfectacionIgv;
	private String tribPorcentajeIgv;
	private String iscCodTipoTributoIsc;
	private BigDecimal iscMontoIsc;
	private BigDecimal iscBaseImponibleIsc;
	private String iscNombreTributo;
	private String iscCodTipoTributo;
	private String iscTipoSistema;
	private String iscPorcentaje;
	private String otroCodTipoTributoOtro;
	private BigDecimal otroMontoTributo;
	private BigDecimal otroBaseImponibleOtro;
	private String otroNombreTributo;
	private String otroCodTipoTributo;
	private String otroPorcentaje;
	private BigDecimal precioVentaUnitario;
	private BigDecimal valorVentaItem;
	private BigDecimal valorReferencialUnitario;
	private BigDecimal valorUnitario;

	public TblDetalleComprobante() {
	}

	public TblDetalleComprobante(int codigoDetalle, TblComprobante tblComprobante) {
		this.codigoDetalle = codigoDetalle;
		this.tblComprobante = tblComprobante;
	}

	public TblDetalleComprobante(int codigoDetalle, TblComprobante tblComprobante, String descripcion, BigDecimal cantidad,
			BigDecimal precioUnitario, BigDecimal descuento, BigDecimal precioTotal, BigDecimal precioFinal,
			String unidadMedida, BigDecimal valorReferencia, String tipoAfectacion, String estado, Date fechaCreacion,
			Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion, String ipCreacion,
			String ipModificacion, String moneda, String codigoProducto, String codigoProductoSunat,
			BigDecimal sumTributosItem, String tribCodTipoTributoIgv, BigDecimal tribMontoIgv,
			BigDecimal tribBaseImponibleIgv, String tribNombreTributo, String tribCodTipoTributo,
			String tribAfectacionIgv, String tribPorcentajeIgv, String iscCodTipoTributoIsc, BigDecimal iscMontoIsc,
			BigDecimal iscBaseImponibleIsc, String iscNombreTributo, String iscCodTipoTributo, String iscTipoSistema,
			String iscPorcentaje, String otroCodTipoTributoOtro, BigDecimal otroMontoTributo,
			BigDecimal otroBaseImponibleOtro, String otroNombreTributo, String otroCodTipoTributo,
			String otroPorcentaje, BigDecimal precioVentaUnitario, BigDecimal valorVentaItem,
			BigDecimal valorReferencialUnitario,BigDecimal valorUnitario) {
		this.codigoDetalle = codigoDetalle;
		this.tblComprobante = tblComprobante;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.precioUnitario = precioUnitario;
		this.descuento = descuento;
		this.precioTotal = precioTotal;
		this.precioFinal = precioFinal;
		this.unidadMedida = unidadMedida;
		this.valorReferencia = valorReferencia;
		this.tipoAfectacion = tipoAfectacion;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.moneda = moneda;
		this.codigoProducto = codigoProducto;
		this.codigoProductoSunat = codigoProductoSunat;
		this.sumTributosItem = sumTributosItem;
		this.tribCodTipoTributoIgv = tribCodTipoTributoIgv;
		this.tribMontoIgv = tribMontoIgv;
		this.tribBaseImponibleIgv = tribBaseImponibleIgv;
		this.tribNombreTributo = tribNombreTributo;
		this.tribCodTipoTributo = tribCodTipoTributo;
		this.tribAfectacionIgv = tribAfectacionIgv;
		this.tribPorcentajeIgv = tribPorcentajeIgv;
		this.iscCodTipoTributoIsc = iscCodTipoTributoIsc;
		this.iscMontoIsc = iscMontoIsc;
		this.iscBaseImponibleIsc = iscBaseImponibleIsc;
		this.iscNombreTributo = iscNombreTributo;
		this.iscCodTipoTributo = iscCodTipoTributo;
		this.iscTipoSistema = iscTipoSistema;
		this.iscPorcentaje = iscPorcentaje;
		this.otroCodTipoTributoOtro = otroCodTipoTributoOtro;
		this.otroMontoTributo = otroMontoTributo;
		this.otroBaseImponibleOtro = otroBaseImponibleOtro;
		this.otroNombreTributo = otroNombreTributo;
		this.otroCodTipoTributo = otroCodTipoTributo;
		this.otroPorcentaje = otroPorcentaje;
		this.precioVentaUnitario = precioVentaUnitario;
		this.valorVentaItem = valorVentaItem;
		this.valorReferencialUnitario = valorReferencialUnitario;
		this.valorUnitario = valorUnitario;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_detalle", unique = true, nullable = false)
	public int getCodigoDetalle() {
		return this.codigoDetalle;
	}

	public void setCodigoDetalle(int codigoDetalle) {
		this.codigoDetalle = codigoDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comprobante", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblComprobante getTblComprobante() {
		return this.tblComprobante;
	}

	public void setTblComprobante(TblComprobante tblComprobante) {
		this.tblComprobante = tblComprobante;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "cantidad", precision = 23, scale = 10)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio_unitario", precision = 23, scale = 10)
	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "descuento", precision = 12)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "precio_total", precision = 12)
	public BigDecimal getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(BigDecimal precioTotal) {
		this.precioTotal = precioTotal;
	}

	@Column(name = "precio_final", precision = 12)
	public BigDecimal getPrecioFinal() {
		return this.precioFinal;
	}

	public void setPrecioFinal(BigDecimal precioFinal) {
		this.precioFinal = precioFinal;
	}

	@Column(name = "unidad_medida", length = 8)
	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	@Column(name = "valor_referencia", precision = 12)
	public BigDecimal getValorReferencia() {
		return this.valorReferencia;
	}

	public void setValorReferencia(BigDecimal valorReferencia) {
		this.valorReferencia = valorReferencia;
	}

	@Column(name = "tipo_afectacion", length = 8)
	public String getTipoAfectacion() {
		return this.tipoAfectacion;
	}

	public void setTipoAfectacion(String tipoAfectacion) {
		this.tipoAfectacion = tipoAfectacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "moneda", length = 8)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "codigo_producto", length = 30)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "codigo_producto_sunat", length = 8)
	public String getCodigoProductoSunat() {
		return this.codigoProductoSunat;
	}

	public void setCodigoProductoSunat(String codigoProductoSunat) {
		this.codigoProductoSunat = codigoProductoSunat;
	}

	@Column(name = "sum_tributos_item", precision = 15)
	public BigDecimal getSumTributosItem() {
		return this.sumTributosItem;
	}

	public void setSumTributosItem(BigDecimal sumTributosItem) {
		this.sumTributosItem = sumTributosItem;
	}

	@Column(name = "trib_cod_tipo_tributo_igv", length = 8)
	public String getTribCodTipoTributoIgv() {
		return this.tribCodTipoTributoIgv;
	}

	public void setTribCodTipoTributoIgv(String tribCodTipoTributoIgv) {
		this.tribCodTipoTributoIgv = tribCodTipoTributoIgv;
	}

	@Column(name = "trib_monto_igv", precision = 15)
	public BigDecimal getTribMontoIgv() {
		return this.tribMontoIgv;
	}

	public void setTribMontoIgv(BigDecimal tribMontoIgv) {
		this.tribMontoIgv = tribMontoIgv;
	}

	@Column(name = "trib_base_imponible_igv", precision = 15)
	public BigDecimal getTribBaseImponibleIgv() {
		return this.tribBaseImponibleIgv;
	}

	public void setTribBaseImponibleIgv(BigDecimal tribBaseImponibleIgv) {
		this.tribBaseImponibleIgv = tribBaseImponibleIgv;
	}

	@Column(name = "trib_nombre_tributo", length = 4)
	public String getTribNombreTributo() {
		return this.tribNombreTributo;
	}

	public void setTribNombreTributo(String tribNombreTributo) {
		this.tribNombreTributo = tribNombreTributo;
	}

	@Column(name = "trib_cod_tipo_tributo", length = 8)
	public String getTribCodTipoTributo() {
		return this.tribCodTipoTributo;
	}

	public void setTribCodTipoTributo(String tribCodTipoTributo) {
		this.tribCodTipoTributo = tribCodTipoTributo;
	}

	@Column(name = "trib_afectacion_igv", length = 8)
	public String getTribAfectacionIgv() {
		return this.tribAfectacionIgv;
	}

	public void setTribAfectacionIgv(String tribAfectacionIgv) {
		this.tribAfectacionIgv = tribAfectacionIgv;
	}

	@Column(name = "trib_porcentaje_igv", length = 5)
	public String getTribPorcentajeIgv() {
		return this.tribPorcentajeIgv;
	}

	public void setTribPorcentajeIgv(String tribPorcentajeIgv) {
		this.tribPorcentajeIgv = tribPorcentajeIgv;
	}

	@Column(name = "isc_cod_tipo_tributo_isc", length = 8)
	public String getIscCodTipoTributoIsc() {
		return this.iscCodTipoTributoIsc;
	}

	public void setIscCodTipoTributoIsc(String iscCodTipoTributoIsc) {
		this.iscCodTipoTributoIsc = iscCodTipoTributoIsc;
	}

	@Column(name = "isc_monto_isc", precision = 15)
	public BigDecimal getIscMontoIsc() {
		return this.iscMontoIsc;
	}

	public void setIscMontoIsc(BigDecimal iscMontoIsc) {
		this.iscMontoIsc = iscMontoIsc;
	}

	@Column(name = "isc_base_imponible_isc", precision = 15)
	public BigDecimal getIscBaseImponibleIsc() {
		return this.iscBaseImponibleIsc;
	}

	public void setIscBaseImponibleIsc(BigDecimal iscBaseImponibleIsc) {
		this.iscBaseImponibleIsc = iscBaseImponibleIsc;
	}

	@Column(name = "isc_nombre_tributo", length = 8)
	public String getIscNombreTributo() {
		return this.iscNombreTributo;
	}

	public void setIscNombreTributo(String iscNombreTributo) {
		this.iscNombreTributo = iscNombreTributo;
	}

	@Column(name = "isc_cod_tipo_tributo", length = 8)
	public String getIscCodTipoTributo() {
		return this.iscCodTipoTributo;
	}

	public void setIscCodTipoTributo(String iscCodTipoTributo) {
		this.iscCodTipoTributo = iscCodTipoTributo;
	}

	@Column(name = "isc_tipo_sistema", length = 8)
	public String getIscTipoSistema() {
		return this.iscTipoSistema;
	}

	public void setIscTipoSistema(String iscTipoSistema) {
		this.iscTipoSistema = iscTipoSistema;
	}

	@Column(name = "isc_porcentaje", length = 8)
	public String getIscPorcentaje() {
		return this.iscPorcentaje;
	}

	public void setIscPorcentaje(String iscPorcentaje) {
		this.iscPorcentaje = iscPorcentaje;
	}

	@Column(name = "otro_cod_tipo_tributo_otro", length = 8)
	public String getOtroCodTipoTributoOtro() {
		return this.otroCodTipoTributoOtro;
	}

	public void setOtroCodTipoTributoOtro(String otroCodTipoTributoOtro) {
		this.otroCodTipoTributoOtro = otroCodTipoTributoOtro;
	}

	@Column(name = "otro_monto_tributo", precision = 15)
	public BigDecimal getOtroMontoTributo() {
		return this.otroMontoTributo;
	}

	public void setOtroMontoTributo(BigDecimal otroMontoTributo) {
		this.otroMontoTributo = otroMontoTributo;
	}

	@Column(name = "otro_base_imponible_otro", precision = 15)
	public BigDecimal getOtroBaseImponibleOtro() {
		return this.otroBaseImponibleOtro;
	}

	public void setOtroBaseImponibleOtro(BigDecimal otroBaseImponibleOtro) {
		this.otroBaseImponibleOtro = otroBaseImponibleOtro;
	}

	@Column(name = "otro_nombre_tributo", length = 8)
	public String getOtroNombreTributo() {
		return this.otroNombreTributo;
	}

	public void setOtroNombreTributo(String otroNombreTributo) {
		this.otroNombreTributo = otroNombreTributo;
	}

	@Column(name = "otro_cod_tipo_tributo", length = 8)
	public String getOtroCodTipoTributo() {
		return this.otroCodTipoTributo;
	}

	public void setOtroCodTipoTributo(String otroCodTipoTributo) {
		this.otroCodTipoTributo = otroCodTipoTributo;
	}

	@Column(name = "otro_porcentaje", length = 8)
	public String getOtroPorcentaje() {
		return this.otroPorcentaje;
	}

	public void setOtroPorcentaje(String otroPorcentaje) {
		this.otroPorcentaje = otroPorcentaje;
	}

	@Column(name = "precio_venta_unitario", precision = 23, scale = 10)
	public BigDecimal getPrecioVentaUnitario() {
		return this.precioVentaUnitario;
	}

	public void setPrecioVentaUnitario(BigDecimal precioVentaUnitario) {
		this.precioVentaUnitario = precioVentaUnitario;
	}

	@Column(name = "valor_venta_item", precision = 15)
	public BigDecimal getValorVentaItem() {
		return this.valorVentaItem;
	}

	public void setValorVentaItem(BigDecimal valorVentaItem) {
		this.valorVentaItem = valorVentaItem;
	}

	@Column(name = "valor_referencial_unitario", precision = 23, scale = 10)
	public BigDecimal getValorReferencialUnitario() {
		return this.valorReferencialUnitario;
	}

	public void setValorReferencialUnitario(BigDecimal valorReferencialUnitario) {
		this.valorReferencialUnitario = valorReferencialUnitario;
	}

	@Column(name = "valor_unitario", precision = 23, scale = 10)
	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}
	
	public void setAuditoriaCreacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(auditoriaBean.getIpCreacion());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			this.setUsuarioCreacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}
	}
	
	public void setAuditoriaModificacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(auditoriaBean.getIpCreacion());
			
			this.setUsuarioModificacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}
	}
}
