package com.pe.lima.sg.facturador.entity;
// Generated 26/12/2017 09:47:33 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.facturador.bean.AuditoriaBean;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblLeyenda generated by hbm2java
 */
@Entity
@Table(name = "tbl_leyenda", schema = "ope")
public class TblLeyenda implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoLeyenda;
	private TblComprobante tblComprobante;
	private String codigoSunat;
	private String descripcionSunat;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String nombreArchivo;

	public TblLeyenda() {
	}

	public TblLeyenda(int codigoLeyenda, TblComprobante tblComprobante) {
		this.codigoLeyenda = codigoLeyenda;
		this.tblComprobante = tblComprobante;
	}

	public TblLeyenda(int codigoLeyenda, TblComprobante tblComprobante, String codigoSunat, String descripcionSunat,
			String estado, Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion,
			Integer usuarioModificacion, String ipCreacion, String ipModificacion,String nombreArchivo) {
		this.codigoLeyenda = codigoLeyenda;
		this.tblComprobante = tblComprobante;
		this.codigoSunat = codigoSunat;
		this.descripcionSunat = descripcionSunat;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.nombreArchivo = nombreArchivo;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_leyenda", unique = true, nullable = false)
	public int getCodigoLeyenda() {
		return this.codigoLeyenda;
	}

	public void setCodigoLeyenda(int codigoLeyenda) {
		this.codigoLeyenda = codigoLeyenda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comprobante", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblComprobante getTblComprobante() {
		return this.tblComprobante;
	}

	public void setTblComprobante(TblComprobante tblComprobante) {
		this.tblComprobante = tblComprobante;
	}

	@Column(name = "codigo_sunat", length = 8)
	public String getCodigoSunat() {
		return this.codigoSunat;
	}

	public void setCodigoSunat(String codigoSunat) {
		this.codigoSunat = codigoSunat;
	}

	@Column(name = "descripcion_sunat", length = 100)
	public String getDescripcionSunat() {
		return this.descripcionSunat;
	}

	public void setDescripcionSunat(String descripcionSunat) {
		this.descripcionSunat = descripcionSunat;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}
	public void setAuditoriaCreacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(auditoriaBean.getIpCreacion());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			this.setUsuarioCreacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}
	}
	
	public void setAuditoriaModificacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(auditoriaBean.getIpCreacion());
			
			this.setUsuarioModificacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}
	}
}
