package com.pe.lima.sg.facturador.entity;
// Generated 7/01/2018 06:30:19 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblNota generated by hbm2java
 */
@Entity
@Table(name = "tbl_nota", schema = "ope")
public class TblNota implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoNota;
	private TblComprobante tblComprobante;
	private String codigoDomicilio;
	private String fechaEmision;
	private String tipoComprobante;
	private String tipoNota;
	private String descripcionNota;
	private String tipoComprobanteAfecta;
	private String serie;
	private String numero;
	private String tipoDocumento;
	private String numeroDocumento;
	private String nombreCliente;
	private String direccionCliente;
	private String moneda;
	private BigDecimal totalOtrosCargos;
	private BigDecimal totalOpGravada;
	private BigDecimal totalOpInafecta;
	private BigDecimal totalOpExonerada;
	private BigDecimal totalIgv;
	private BigDecimal sumatoriaIsc;
	private BigDecimal sumatorioaOtrosTributos;
	private BigDecimal totalImporte;
	private String estadoOperacion;
	private String codigoVerificacion;
	private String tipoOperacion;
	private String horaEmision;
	private BigDecimal sumTributo;
	private BigDecimal totValorVenta;
	private BigDecimal totPrecioVenta;
	private BigDecimal totDescuento;
	private BigDecimal totAnticipo;
	private BigDecimal sumOtrosCargos;
	private String versionUbl;
	private String customizacionDocumento;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipModificacion;
	private String ipCreacion;
	private Set<TblBandejaFacturadorNota> tblBandejaFacturadorNotas = new HashSet<TblBandejaFacturadorNota>(0);
	private Set<TblTributoGeneralNota> tblTributoGeneralNotas = new HashSet<>(0);
	private Set<TblSunatCabeceraNota> tblSunatCabeceraNotas = new HashSet<TblSunatCabeceraNota>(0);
	private Set<TblDetalleNota> tblDetalleNotas = new HashSet<TblDetalleNota>(0);
	private Set<TblLeyendaNota> tblLeyendaNotas = new HashSet<TblLeyendaNota>(0);
	private TblEmpresa tblEmpresa;

	public TblNota() {
	}

	public TblNota(int codigoNota, TblComprobante tblComprobante) {
		this.codigoNota = codigoNota;
		this.tblComprobante = tblComprobante;
	}

	public TblNota(int codigoNota, TblComprobante tblComprobante, String codigoDomicilio, String fechaEmision,
			String tipoComprobante, String tipoNota, String descripcionNota, String tipoComprobanteAfecta, String serie,
			String numero, String tipoDocumento, String numeroDocumento, String nombreCliente, String direccionCliente,
			String moneda, BigDecimal totalOtrosCargos, BigDecimal totalOpGravada, BigDecimal totalOpInafecta,
			BigDecimal totalOpExonerada, BigDecimal totalIgv, BigDecimal sumatoriaIsc, BigDecimal sumOtrosCargos,
			BigDecimal sumatorioaOtrosTributos, BigDecimal totalImporte, String estadoOperacion, String codigoVerificacion, String estado,
			Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion, Set<TblLeyendaNota> tblLeyendaNotas, Set<TblTributoGeneralNota> tblTributoGeneralNotas,
			String ipModificacion, String ipCreacion, Set<TblBandejaFacturadorNota> tblBandejaFacturadorNotas, Set<TblSunatCabeceraNota> tblSunatCabeceraNotas,
			String tipoOperacion, String horaEmision, BigDecimal sumTributo, BigDecimal totValorVenta,
			BigDecimal totPrecioVenta, BigDecimal totDescuento, BigDecimal totAnticipo, String versionUbl,
			String customizacionDocumento,Set<TblDetalleNota> tblDetalleNotas, TblEmpresa tblEmpresa) {
		this.codigoNota = codigoNota;
		this.tblComprobante = tblComprobante;
		this.codigoDomicilio = codigoDomicilio;
		this.fechaEmision = fechaEmision;
		this.tipoComprobante = tipoComprobante;
		this.tipoNota = tipoNota;
		this.descripcionNota = descripcionNota;
		this.tipoComprobanteAfecta = tipoComprobanteAfecta;
		this.serie = serie;
		this.numero = numero;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.nombreCliente = nombreCliente;
		this.direccionCliente = direccionCliente;
		this.moneda = moneda;
		this.totalOtrosCargos = totalOtrosCargos;
		this.totalOpGravada = totalOpGravada;
		this.totalOpInafecta = totalOpInafecta;
		this.totalOpExonerada = totalOpExonerada;
		this.totalIgv = totalIgv;
		this.sumatoriaIsc = sumatoriaIsc;
		this.sumatorioaOtrosTributos = sumatorioaOtrosTributos;
		this.totalImporte = totalImporte;
		this.estadoOperacion = estadoOperacion;
		this.estado = estado;
		this.codigoVerificacion = codigoVerificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipModificacion = ipModificacion;
		this.ipCreacion = ipCreacion;
		this.tipoOperacion = tipoOperacion;
		this.horaEmision = horaEmision;
		this.sumTributo = sumTributo;
		this.totValorVenta = totValorVenta;
		this.totPrecioVenta = totPrecioVenta;
		this.totDescuento = totDescuento;
		this.totAnticipo = totAnticipo;
		this.versionUbl = versionUbl;
		this.customizacionDocumento = customizacionDocumento;
		this.sumOtrosCargos = sumOtrosCargos;
		this.tblLeyendaNotas = tblLeyendaNotas;
		this.tblTributoGeneralNotas = tblTributoGeneralNotas;
		this.tblBandejaFacturadorNotas = tblBandejaFacturadorNotas;
		this.tblSunatCabeceraNotas = tblSunatCabeceraNotas;
		this.tblDetalleNotas = tblDetalleNotas;
		this.tblEmpresa = tblEmpresa;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_nota", unique = true, nullable = false)
	public int getCodigoNota() {
		return this.codigoNota;
	}


	public void setCodigoNota(int codigoNota) {
		this.codigoNota = codigoNota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comprobante", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblComprobante getTblComprobante() {
		return this.tblComprobante;
	}

	public void setTblComprobante(TblComprobante tblComprobante) {
		this.tblComprobante = tblComprobante;
	}

	@Column(name = "codigo_domicilio", length = 8)
	public String getCodigoDomicilio() {
		return this.codigoDomicilio;
	}

	public void setCodigoDomicilio(String codigoDomicilio) {
		this.codigoDomicilio = codigoDomicilio;
	}

	@Column(name = "fecha_emision", length = 10)
	public String getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(String fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "tipo_comprobante", length = 8)
	public String getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(String tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	@Column(name = "tipo_nota", length = 8)
	public String getTipoNota() {
		return this.tipoNota;
	}

	public void setTipoNota(String tipoNota) {
		this.tipoNota = tipoNota;
	}

	@Column(name = "descripcion_nota", length = 250)
	public String getDescripcionNota() {
		return this.descripcionNota;
	}

	public void setDescripcionNota(String descripcionNota) {
		this.descripcionNota = descripcionNota;
	}

	@Column(name = "tipo_comprobante_afecta", length = 8)
	public String getTipoComprobanteAfecta() {
		return this.tipoComprobanteAfecta;
	}

	public void setTipoComprobanteAfecta(String tipoComprobanteAfecta) {
		this.tipoComprobanteAfecta = tipoComprobanteAfecta;
	}

	@Column(name = "serie", length = 8)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "numero", length = 16)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "tipo_documento", length = 8)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero_documento", length = 32)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "nombre_cliente", length = 256)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	@Column(name = "direccion_cliente", length = 256)
	public String getDireccionCliente() {
		return this.direccionCliente;
	}

	public void setDireccionCliente(String direccionCliente) {
		this.direccionCliente = direccionCliente;
	}

	@Column(name = "moneda", length = 8)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "total_otros_cargos", precision = 12)
	public BigDecimal getTotalOtrosCargos() {
		return this.totalOtrosCargos;
	}

	public void setTotalOtrosCargos(BigDecimal totalOtrosCargos) {
		this.totalOtrosCargos = totalOtrosCargos;
	}

	@Column(name = "total_op_gravada", precision = 12)
	public BigDecimal getTotalOpGravada() {
		return this.totalOpGravada;
	}

	public void setTotalOpGravada(BigDecimal totalOpGravada) {
		this.totalOpGravada = totalOpGravada;
	}

	@Column(name = "total_op_inafecta", precision = 12)
	public BigDecimal getTotalOpInafecta() {
		return this.totalOpInafecta;
	}

	public void setTotalOpInafecta(BigDecimal totalOpInafecta) {
		this.totalOpInafecta = totalOpInafecta;
	}

	@Column(name = "total_op_exonerada", precision = 12)
	public BigDecimal getTotalOpExonerada() {
		return this.totalOpExonerada;
	}

	public void setTotalOpExonerada(BigDecimal totalOpExonerada) {
		this.totalOpExonerada = totalOpExonerada;
	}

	@Column(name = "total_igv", precision = 12)
	public BigDecimal getTotalIgv() {
		return this.totalIgv;
	}

	public void setTotalIgv(BigDecimal totalIgv) {
		this.totalIgv = totalIgv;
	}

	@Column(name = "sumatoria_isc", precision = 12)
	public BigDecimal getSumatoriaIsc() {
		return this.sumatoriaIsc;
	}

	public void setSumatoriaIsc(BigDecimal sumatoriaIsc) {
		this.sumatoriaIsc = sumatoriaIsc;
	}

	@Column(name = "sumatorioa_otros_tributos", precision = 12)
	public BigDecimal getSumatorioaOtrosTributos() {
		return this.sumatorioaOtrosTributos;
	}

	public void setSumatorioaOtrosTributos(BigDecimal sumatorioaOtrosTributos) {
		this.sumatorioaOtrosTributos = sumatorioaOtrosTributos;
	}

	@Column(name = "total_importe", precision = 12)
	public BigDecimal getTotalImporte() {
		return this.totalImporte;
	}

	public void setTotalImporte(BigDecimal totalImporte) {
		this.totalImporte = totalImporte;
	}

	@Column(name = "estado_operacion", length = 8)
	public String getEstadoOperacion() {
		return this.estadoOperacion;
	}

	public void setEstadoOperacion(String estadoOperacion) {
		this.estadoOperacion = estadoOperacion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "tipo_operacion", length = 4)
	public String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	@Column(name = "hora_emision", length = 14)
	public String getHoraEmision() {
		return this.horaEmision;
	}

	public void setHoraEmision(String horaEmision) {
		this.horaEmision = horaEmision;
	}

	@Column(name = "sum_tributo", precision = 15)
	public BigDecimal getSumTributo() {
		return this.sumTributo;
	}

	public void setSumTributo(BigDecimal sumTributo) {
		this.sumTributo = sumTributo;
	}

	@Column(name = "tot_valor_venta", precision = 15)
	public BigDecimal getTotValorVenta() {
		return this.totValorVenta;
	}

	public void setTotValorVenta(BigDecimal totValorVenta) {
		this.totValorVenta = totValorVenta;
	}

	@Column(name = "tot_precio_venta", precision = 15)
	public BigDecimal getTotPrecioVenta() {
		return this.totPrecioVenta;
	}

	public void setTotPrecioVenta(BigDecimal totPrecioVenta) {
		this.totPrecioVenta = totPrecioVenta;
	}

	@Column(name = "tot_descuento", precision = 15)
	public BigDecimal getTotDescuento() {
		return this.totDescuento;
	}

	public void setTotDescuento(BigDecimal totDescuento) {
		this.totDescuento = totDescuento;
	}

	@Column(name = "tot_anticipo", precision = 15)
	public BigDecimal getTotAnticipo() {
		return this.totAnticipo;
	}

	public void setTotAnticipo(BigDecimal totAnticipo) {
		this.totAnticipo = totAnticipo;
	}
	
	@Column(name = "sum_otros_cargos", precision = 15)
	public BigDecimal getSumOtrosCargos() {
		return this.sumOtrosCargos;
	}

	public void setSumOtrosCargos(BigDecimal sumOtrosCargos) {
		this.sumOtrosCargos = sumOtrosCargos;
	}

	@Column(name = "version_ubl", length = 3)
	public String getVersionUbl() {
		return this.versionUbl;
	}

	public void setVersionUbl(String versionUbl) {
		this.versionUbl = versionUbl;
	}

	@Column(name = "customizacion_documento", length = 3)
	public String getCustomizacionDocumento() {
		return this.customizacionDocumento;
	}

	public void setCustomizacionDocumento(String customizacionDocumento) {
		this.customizacionDocumento = customizacionDocumento;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblNota")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblLeyendaNota> getTblLeyendaNotas() {
		return this.tblLeyendaNotas;
	}

	public void setTblLeyendaNotas(Set<TblLeyendaNota> tblLeyendaNotas) {
		this.tblLeyendaNotas = tblLeyendaNotas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblNota")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblTributoGeneralNota> getTblTributoGeneralNotas() {
		return this.tblTributoGeneralNotas;
	}

	public void setTblTributoGeneralNotas(Set<TblTributoGeneralNota> tblTributoGeneralNotas) {
		this.tblTributoGeneralNotas = tblTributoGeneralNotas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblNota")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblBandejaFacturadorNota> getTblBandejaFacturadorNotas() {
		return this.tblBandejaFacturadorNotas;
	}

	public void setTblBandejaFacturadorNotas(Set<TblBandejaFacturadorNota> tblBandejaFacturadorNotas) {
		this.tblBandejaFacturadorNotas = tblBandejaFacturadorNotas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblNota")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblSunatCabeceraNota> getTblSunatCabeceraNotas() {
		return this.tblSunatCabeceraNotas;
	}

	public void setTblSunatCabeceraNotas(Set<TblSunatCabeceraNota> tblSunatCabeceraNotas) {
		this.tblSunatCabeceraNotas = tblSunatCabeceraNotas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblNota")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblDetalleNota> getTblDetalleNotas() {
		return this.tblDetalleNotas;
	}

	public void setTblDetalleNotas(Set<TblDetalleNota> tblDetalleNotas) {
		this.tblDetalleNotas = tblDetalleNotas;
	}

	@Column(name = "codigo_verificacion", length = 64)
	public String getCodigoVerificacion() {
		return codigoVerificacion;
	}

	public void setCodigoVerificacion(String codigoVerificacion) {
		this.codigoVerificacion = codigoVerificacion;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_entidad", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblEmpresa getTblEmpresa() {
		return this.tblEmpresa;
	}

	public void setTblEmpresa(TblEmpresa tblEmpresa) {
		this.tblEmpresa = tblEmpresa;
	}

	public void setAuditoriaCreacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(request.getRemoteAddr());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioCreacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
	
	public void setAuditoriaModificacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(request.getRemoteAddr());
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioModificacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
}
