package com.pe.lima.sg.facturador.entity;
// Generated 21/10/2018 12:31:49 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblSunatTributoGeneralNota generated by hbm2java
 */
@Entity
@Table(name = "tbl_sunat_tributo_general_nota", schema = "ope")
public class TblSunatTributoGeneralNota implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoTributoGeneral;
	private TblSunatCabeceraNota tblSunatCabeceraNota;
	private String identificadorTributo;
	private String nombreTributo;
	private String codigoTipoTributo;
	private String baseImponible;
	private String montoTributoItem;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String nombreArchivo;

	public TblSunatTributoGeneralNota() {
	}

	public TblSunatTributoGeneralNota(int codigoTributoGeneral, TblSunatCabeceraNota tblSunatCabeceraNota) {
		this.codigoTributoGeneral = codigoTributoGeneral;
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
	}

	public TblSunatTributoGeneralNota(int codigoTributoGeneral, TblSunatCabeceraNota tblSunatCabeceraNota,
			String identificadorTributo, String nombreTributo, String codigoTipoTributo, String baseImponible,
			String montoTributoItem, String estado, Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion,
			Integer usuarioModificacion, String ipCreacion, String ipModificacion, String nombreArchivo) {
		this.codigoTributoGeneral = codigoTributoGeneral;
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
		this.identificadorTributo = identificadorTributo;
		this.nombreTributo = nombreTributo;
		this.codigoTipoTributo = codigoTipoTributo;
		this.baseImponible = baseImponible;
		this.montoTributoItem = montoTributoItem;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.nombreArchivo = nombreArchivo;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_tributo_general", unique = true, nullable = false)
	public int getCodigoTributoGeneral() {
		return this.codigoTributoGeneral;
	}

	public void setCodigoTributoGeneral(int codigoTributoGeneral) {
		this.codigoTributoGeneral = codigoTributoGeneral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cabecera", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblSunatCabeceraNota getTblSunatCabeceraNota() {
		return this.tblSunatCabeceraNota;
	}

	public void setTblSunatCabeceraNota(TblSunatCabeceraNota tblSunatCabeceraNota) {
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
	}

	@Column(name = "identificador_tributo", length = 4)
	public String getIdentificadorTributo() {
		return this.identificadorTributo;
	}

	public void setIdentificadorTributo(String identificadorTributo) {
		this.identificadorTributo = identificadorTributo;
	}

	@Column(name = "nombre_tributo", length = 4)
	public String getNombreTributo() {
		return this.nombreTributo;
	}

	public void setNombreTributo(String nombreTributo) {
		this.nombreTributo = nombreTributo;
	}

	@Column(name = "codigo_tipo_tributo", length = 4)
	public String getCodigoTipoTributo() {
		return this.codigoTipoTributo;
	}

	public void setCodigoTipoTributo(String codigoTipoTributo) {
		this.codigoTipoTributo = codigoTipoTributo;
	}

	@Column(name = "base_imponible", length = 15)
	public String getBaseImponible() {
		return this.baseImponible;
	}

	public void setBaseImponible(String baseImponible) {
		this.baseImponible = baseImponible;
	}

	@Column(name = "monto_tributo_item", length = 15)
	public String getMontoTributoItem() {
		return this.montoTributoItem;
	}

	public void setMontoTributoItem(String montoTributoItem) {
		this.montoTributoItem = montoTributoItem;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}


	public void setAuditoriaCreacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(request.getRemoteAddr());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioCreacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
	
	public void setAuditoriaModificacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(request.getRemoteAddr());
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioModificacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
}
