package com.pe.lima.sg.facturador.entity;
// Generated 7/01/2018 06:30:19 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblSunatDetalleNota generated by hbm2java
 */
@Entity
@Table(name = "tbl_sunat_detalle_nota", schema = "ope")
public class TblSunatDetalleNota implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoDetalle;
	private TblSunatCabeceraNota tblSunatCabeceraNota;
	private String codigoUnidad;
	private String cantidad;
	private String codigoProducto;
	private String codigoProductoSunat;
	private String descripcion;
	private String valorUnitario;
	private String descuento;
	private String montoIgv;
	private String afectacionIgv;
	private String montoIsc;
	private String tipoIsc;
	private String precioVentaUnitario;
	private String valorVentaItem;
	private String nombreArchivo;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private String sumTributosItem;
	private String tribCodTipoTributoIgv;
	private String tribMontoIgv;
	private String tribBaseImponibleIgv;
	private String tribNombreTributo;
	private String tribCodTipoTributo;
	private String tribAfectacionIgv;
	private String tribPorcentajeIgv;
	private String iscCodTipoTributoIsc;
	private String iscMontoIsc;
	private String iscBaseImponibleIsc;
	private String iscNombreTributo;
	private String iscCodTipoTributo;
	private String iscTipoSistema;
	private String iscPorcentaje;
	private String otroCodTipoTributoOtro;
	private String otroMontoTributo;
	private String otroBaseImponibleOtro;
	private String otroNombreTributo;
	private String otroCodTipoTributo;
	private String otroPorcentaje;
	private String valorReferencialUnitario;

	public TblSunatDetalleNota() {
	}

	public TblSunatDetalleNota(int codigoDetalle, TblSunatCabeceraNota tblSunatCabeceraNota) {
		this.codigoDetalle = codigoDetalle;
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
	}

	public TblSunatDetalleNota(int codigoDetalle, TblSunatCabeceraNota tblSunatCabeceraNota, String codigoUnidad,
			String cantidad, String codigoProducto, String codigoProductoSunat, String descripcion,
			String valorUnitario, String descuento, String montoIgv, String afectacionIgv, String montoIsc,
			String tipoIsc, String precioVentaUnitario, String valorVentaItem, String nombreArchivo, String estado,
			Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion,
			String ipCreacion, String ipModificacion, String sumTributosItem, String tribCodTipoTributoIgv,
			String tribMontoIgv, String tribBaseImponibleIgv, String tribNombreTributo, String tribCodTipoTributo,
			String tribAfectacionIgv, String tribPorcentajeIgv, String iscCodTipoTributoIsc, String iscMontoIsc,
			String iscBaseImponibleIsc, String iscNombreTributo, String iscCodTipoTributo, String iscTipoSistema,
			String iscPorcentaje, String otroCodTipoTributoOtro, String otroMontoTributo, String otroBaseImponibleOtro,
			String otroNombreTributo, String otroCodTipoTributo, String otroPorcentaje,
			String valorReferencialUnitario) {
		this.codigoDetalle = codigoDetalle;
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
		this.codigoUnidad = codigoUnidad;
		this.cantidad = cantidad;
		this.codigoProducto = codigoProducto;
		this.codigoProductoSunat = codigoProductoSunat;
		this.descripcion = descripcion;
		this.valorUnitario = valorUnitario;
		this.descuento = descuento;
		this.montoIgv = montoIgv;
		this.afectacionIgv = afectacionIgv;
		this.montoIsc = montoIsc;
		this.tipoIsc = tipoIsc;
		this.precioVentaUnitario = precioVentaUnitario;
		this.valorVentaItem = valorVentaItem;
		this.nombreArchivo = nombreArchivo;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.sumTributosItem = sumTributosItem;
		this.tribCodTipoTributoIgv = tribCodTipoTributoIgv;
		this.tribMontoIgv = tribMontoIgv;
		this.tribBaseImponibleIgv = tribBaseImponibleIgv;
		this.tribNombreTributo = tribNombreTributo;
		this.tribCodTipoTributo = tribCodTipoTributo;
		this.tribAfectacionIgv = tribAfectacionIgv;
		this.tribPorcentajeIgv = tribPorcentajeIgv;
		this.iscCodTipoTributoIsc = iscCodTipoTributoIsc;
		this.iscMontoIsc = iscMontoIsc;
		this.iscBaseImponibleIsc = iscBaseImponibleIsc;
		this.iscNombreTributo = iscNombreTributo;
		this.iscCodTipoTributo = iscCodTipoTributo;
		this.iscTipoSistema = iscTipoSistema;
		this.iscPorcentaje = iscPorcentaje;
		this.otroCodTipoTributoOtro = otroCodTipoTributoOtro;
		this.otroMontoTributo = otroMontoTributo;
		this.otroBaseImponibleOtro = otroBaseImponibleOtro;
		this.otroNombreTributo = otroNombreTributo;
		this.otroCodTipoTributo = otroCodTipoTributo;
		this.otroPorcentaje = otroPorcentaje;
		this.valorReferencialUnitario = valorReferencialUnitario;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_detalle", unique = true, nullable = false)
	public int getCodigoDetalle() {
		return this.codigoDetalle;
	}

	public void setCodigoDetalle(int codigoDetalle) {
		this.codigoDetalle = codigoDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cabecera", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblSunatCabeceraNota getTblSunatCabeceraNota() {
		return this.tblSunatCabeceraNota;
	}

	public void setTblSunatCabeceraNota(TblSunatCabeceraNota tblSunatCabeceraNota) {
		this.tblSunatCabeceraNota = tblSunatCabeceraNota;
	}

	@Column(name = "codigo_unidad", length = 3)
	public String getCodigoUnidad() {
		return this.codigoUnidad;
	}

	public void setCodigoUnidad(String codigoUnidad) {
		this.codigoUnidad = codigoUnidad;
	}

	@Column(name = "cantidad", length = 23)
	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "codigo_producto", length = 30)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "codigo_producto_sunat", length = 20)
	public String getCodigoProductoSunat() {
		return this.codigoProductoSunat;
	}

	public void setCodigoProductoSunat(String codigoProductoSunat) {
		this.codigoProductoSunat = codigoProductoSunat;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor_unitario", length = 23)
	public String getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(String valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Column(name = "descuento", length = 15)
	public String getDescuento() {
		return this.descuento;
	}

	public void setDescuento(String descuento) {
		this.descuento = descuento;
	}

	@Column(name = "monto_igv", length = 15)
	public String getMontoIgv() {
		return this.montoIgv;
	}

	public void setMontoIgv(String montoIgv) {
		this.montoIgv = montoIgv;
	}

	@Column(name = "afectacion_igv", length = 2)
	public String getAfectacionIgv() {
		return this.afectacionIgv;
	}

	public void setAfectacionIgv(String afectacionIgv) {
		this.afectacionIgv = afectacionIgv;
	}

	@Column(name = "monto_isc", length = 15)
	public String getMontoIsc() {
		return this.montoIsc;
	}

	public void setMontoIsc(String montoIsc) {
		this.montoIsc = montoIsc;
	}

	@Column(name = "tipo_isc", length = 2)
	public String getTipoIsc() {
		return this.tipoIsc;
	}

	public void setTipoIsc(String tipoIsc) {
		this.tipoIsc = tipoIsc;
	}

	@Column(name = "precio_venta_unitario", length = 23)
	public String getPrecioVentaUnitario() {
		return this.precioVentaUnitario;
	}

	public void setPrecioVentaUnitario(String precioVentaUnitario) {
		this.precioVentaUnitario = precioVentaUnitario;
	}

	@Column(name = "valor_venta_item", length = 15)
	public String getValorVentaItem() {
		return this.valorVentaItem;
	}

	public void setValorVentaItem(String valorVentaItem) {
		this.valorVentaItem = valorVentaItem;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "sum_tributos_item", length = 15)
	public String getSumTributosItem() {
		return this.sumTributosItem;
	}

	public void setSumTributosItem(String sumTributosItem) {
		this.sumTributosItem = sumTributosItem;
	}

	@Column(name = "trib_cod_tipo_tributo_igv", length = 4)
	public String getTribCodTipoTributoIgv() {
		return this.tribCodTipoTributoIgv;
	}

	public void setTribCodTipoTributoIgv(String tribCodTipoTributoIgv) {
		this.tribCodTipoTributoIgv = tribCodTipoTributoIgv;
	}

	@Column(name = "trib_monto_igv", length = 15)
	public String getTribMontoIgv() {
		return this.tribMontoIgv;
	}

	public void setTribMontoIgv(String tribMontoIgv) {
		this.tribMontoIgv = tribMontoIgv;
	}

	@Column(name = "trib_base_imponible_igv", length = 15)
	public String getTribBaseImponibleIgv() {
		return this.tribBaseImponibleIgv;
	}

	public void setTribBaseImponibleIgv(String tribBaseImponibleIgv) {
		this.tribBaseImponibleIgv = tribBaseImponibleIgv;
	}

	@Column(name = "trib_nombre_tributo", length = 4)
	public String getTribNombreTributo() {
		return this.tribNombreTributo;
	}

	public void setTribNombreTributo(String tribNombreTributo) {
		this.tribNombreTributo = tribNombreTributo;
	}

	@Column(name = "trib_cod_tipo_tributo", length = 4)
	public String getTribCodTipoTributo() {
		return this.tribCodTipoTributo;
	}

	public void setTribCodTipoTributo(String tribCodTipoTributo) {
		this.tribCodTipoTributo = tribCodTipoTributo;
	}

	@Column(name = "trib_afectacion_igv", length = 2)
	public String getTribAfectacionIgv() {
		return this.tribAfectacionIgv;
	}

	public void setTribAfectacionIgv(String tribAfectacionIgv) {
		this.tribAfectacionIgv = tribAfectacionIgv;
	}

	@Column(name = "trib_porcentaje_igv", length = 5)
	public String getTribPorcentajeIgv() {
		return this.tribPorcentajeIgv;
	}

	public void setTribPorcentajeIgv(String tribPorcentajeIgv) {
		this.tribPorcentajeIgv = tribPorcentajeIgv;
	}

	@Column(name = "isc_cod_tipo_tributo_isc", length = 15)
	public String getIscCodTipoTributoIsc() {
		return this.iscCodTipoTributoIsc;
	}

	public void setIscCodTipoTributoIsc(String iscCodTipoTributoIsc) {
		this.iscCodTipoTributoIsc = iscCodTipoTributoIsc;
	}

	@Column(name = "isc_monto_isc", length = 15)
	public String getIscMontoIsc() {
		return this.iscMontoIsc;
	}

	public void setIscMontoIsc(String iscMontoIsc) {
		this.iscMontoIsc = iscMontoIsc;
	}

	@Column(name = "isc_base_imponible_isc", length = 15)
	public String getIscBaseImponibleIsc() {
		return this.iscBaseImponibleIsc;
	}

	public void setIscBaseImponibleIsc(String iscBaseImponibleIsc) {
		this.iscBaseImponibleIsc = iscBaseImponibleIsc;
	}

	@Column(name = "isc_nombre_tributo", length = 4)
	public String getIscNombreTributo() {
		return this.iscNombreTributo;
	}

	public void setIscNombreTributo(String iscNombreTributo) {
		this.iscNombreTributo = iscNombreTributo;
	}

	@Column(name = "isc_cod_tipo_tributo", length = 4)
	public String getIscCodTipoTributo() {
		return this.iscCodTipoTributo;
	}

	public void setIscCodTipoTributo(String iscCodTipoTributo) {
		this.iscCodTipoTributo = iscCodTipoTributo;
	}

	@Column(name = "isc_tipo_sistema", length = 2)
	public String getIscTipoSistema() {
		return this.iscTipoSistema;
	}

	public void setIscTipoSistema(String iscTipoSistema) {
		this.iscTipoSistema = iscTipoSistema;
	}

	@Column(name = "isc_porcentaje", length = 5)
	public String getIscPorcentaje() {
		return this.iscPorcentaje;
	}

	public void setIscPorcentaje(String iscPorcentaje) {
		this.iscPorcentaje = iscPorcentaje;
	}

	@Column(name = "otro_cod_tipo_tributo_otro", length = 4)
	public String getOtroCodTipoTributoOtro() {
		return this.otroCodTipoTributoOtro;
	}

	public void setOtroCodTipoTributoOtro(String otroCodTipoTributoOtro) {
		this.otroCodTipoTributoOtro = otroCodTipoTributoOtro;
	}

	@Column(name = "otro_monto_tributo", length = 15)
	public String getOtroMontoTributo() {
		return this.otroMontoTributo;
	}

	public void setOtroMontoTributo(String otroMontoTributo) {
		this.otroMontoTributo = otroMontoTributo;
	}

	@Column(name = "otro_base_imponible_otro", length = 15)
	public String getOtroBaseImponibleOtro() {
		return this.otroBaseImponibleOtro;
	}

	public void setOtroBaseImponibleOtro(String otroBaseImponibleOtro) {
		this.otroBaseImponibleOtro = otroBaseImponibleOtro;
	}

	@Column(name = "otro_nombre_tributo", length = 4)
	public String getOtroNombreTributo() {
		return this.otroNombreTributo;
	}

	public void setOtroNombreTributo(String otroNombreTributo) {
		this.otroNombreTributo = otroNombreTributo;
	}

	@Column(name = "otro_cod_tipo_tributo", length = 4)
	public String getOtroCodTipoTributo() {
		return this.otroCodTipoTributo;
	}

	public void setOtroCodTipoTributo(String otroCodTipoTributo) {
		this.otroCodTipoTributo = otroCodTipoTributo;
	}

	@Column(name = "otro_porcentaje", length = 5)
	public String getOtroPorcentaje() {
		return this.otroPorcentaje;
	}

	public void setOtroPorcentaje(String otroPorcentaje) {
		this.otroPorcentaje = otroPorcentaje;
	}

	@Column(name = "valor_referencial_unitario", length = 23)
	public String getValorReferencialUnitario() {
		return this.valorReferencialUnitario;
	}

	public void setValorReferencialUnitario(String valorReferencialUnitario) {
		this.valorReferencialUnitario = valorReferencialUnitario;
	}

	public void setAuditoriaCreacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(request.getRemoteAddr());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioCreacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
	
	public void setAuditoriaModificacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(request.getRemoteAddr());
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioModificacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
}
