package com.pe.lima.sg.facturador.entity;
// Generated 14/10/2018 04:35:37 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.facturador.bean.AuditoriaBean;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblSunatTributoGeneral generated by hbm2java
 */
@Entity
@Table(name = "tbl_sunat_tributo_general", schema = "ope")
public class TblSunatTributoGeneral implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoTributoGeneral;
	private String identificadorTributo;
	private String nombreTributo;
	private String codigoTipoTributo;
	private String baseImponible;
	private String montoTributoItem;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private int codigoCabecera;
	private TblSunatCabecera tblSunatCabecera;
	private String nombreArchivo;

	public TblSunatTributoGeneral() {
	}

	public TblSunatTributoGeneral(int codigoTributoGeneral, String identificadorTributo, String nombreTributo,
			String codigoTipoTributo, String baseImponible, String montoTributoItem, String estado, Date fechaCreacion,
			Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion, String ipCreacion,
			String ipModificacion, int codigoCabecera, TblSunatCabecera tblSunatCabecera, String nombreArchivo) {
		this.codigoTributoGeneral = codigoTributoGeneral;
		this.identificadorTributo = identificadorTributo;
		this.nombreTributo = nombreTributo;
		this.codigoTipoTributo = codigoTipoTributo;
		this.baseImponible = baseImponible;
		this.montoTributoItem = montoTributoItem;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoCabecera = codigoCabecera;
		this.tblSunatCabecera = tblSunatCabecera;
		this.nombreArchivo = nombreArchivo;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_tributo_general", nullable = false)
	public int getCodigoTributoGeneral() {
		return this.codigoTributoGeneral;
	}

	public void setCodigoTributoGeneral(int codigoTributoGeneral) {
		this.codigoTributoGeneral = codigoTributoGeneral;
	}

	@Column(name = "identificador_tributo", length = 4)
	public String getIdentificadorTributo() {
		return this.identificadorTributo;
	}

	public void setIdentificadorTributo(String identificadorTributo) {
		this.identificadorTributo = identificadorTributo;
	}

	@Column(name = "nombre_tributo", length = 4)
	public String getNombreTributo() {
		return this.nombreTributo;
	}

	public void setNombreTributo(String nombreTributo) {
		this.nombreTributo = nombreTributo;
	}

	@Column(name = "codigo_tipo_tributo", length = 4)
	public String getCodigoTipoTributo() {
		return this.codigoTipoTributo;
	}

	public void setCodigoTipoTributo(String codigoTipoTributo) {
		this.codigoTipoTributo = codigoTipoTributo;
	}

	@Column(name = "base_imponible", length = 15)
	public String getBaseImponible() {
		return this.baseImponible;
	}

	public void setBaseImponible(String baseImponible) {
		this.baseImponible = baseImponible;
	}

	@Column(name = "monto_tributo_item", length = 15)
	public String getMontoTributoItem() {
		return this.montoTributoItem;
	}

	public void setMontoTributoItem(String montoTributoItem) {
		this.montoTributoItem = montoTributoItem;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "codigo_cabecera", nullable = false)
	public int getCodigoCabecera() {
		return this.codigoCabecera;
	}

	public void setCodigoCabecera(int codigoCabecera) {
		this.codigoCabecera = codigoCabecera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cabecera", nullable = false, insertable = false, updatable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblSunatCabecera getTblSunatCabecera() {
		return this.tblSunatCabecera;
	}

	public void setTblSunatCabecera(TblSunatCabecera tblSunatCabecera) {
		this.tblSunatCabecera = tblSunatCabecera;
	}

	@Column(name = "nombre_archivo", length = 128)
	public String getNombreArchivo() {
		return nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}
	
	public void setAuditoriaCreacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(auditoriaBean.getIpCreacion());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			this.setUsuarioCreacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}
	}
	
	public void setAuditoriaModificacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(auditoriaBean.getIpCreacion());
			
			this.setUsuarioModificacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}
	}

}
