package com.pe.lima.sg.facturador.entity;
// Generated 14/10/2018 04:35:37 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.pe.lima.sg.facturador.bean.AuditoriaBean;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblTributoGeneral generated by hbm2java
 */
@Entity
@Table(name = "tbl_tributo_general", schema = "ope")
public class TblTributoGeneral implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoTributoGeneral;
	private String identificadorTributo;
	private String nombreTributo;
	private String codigoTipoTributo;
	private BigDecimal baseImponible;
	private BigDecimal montoTributoItem;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private int codigoComprobante;
	private TblComprobante tblComprobante;

	public TblTributoGeneral() {
	}

	public TblTributoGeneral(int codigoTributoGeneral, String identificadorTributo, String nombreTributo,
			String codigoTipoTributo, BigDecimal baseImponible, BigDecimal montoTributoItem, String estado,
			Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion,
			String ipCreacion, String ipModificacion, int codigoComprobante, TblComprobante tblComprobante) {
		this.codigoTributoGeneral = codigoTributoGeneral;
		this.identificadorTributo = identificadorTributo;
		this.nombreTributo = nombreTributo;
		this.codigoTipoTributo = codigoTipoTributo;
		this.baseImponible = baseImponible;
		this.montoTributoItem = montoTributoItem;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.codigoComprobante = codigoComprobante;
		this.tblComprobante = tblComprobante;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_tributo_general", nullable = false)
	public int getCodigoTributoGeneral() {
		return this.codigoTributoGeneral;
	}

	public void setCodigoTributoGeneral(int codigoTributoGeneral) {
		this.codigoTributoGeneral = codigoTributoGeneral;
	}

	@Column(name = "identificador_tributo", precision = 4, scale = 0)
	public String getIdentificadorTributo() {
		return this.identificadorTributo;
	}

	public void setIdentificadorTributo(String identificadorTributo) {
		this.identificadorTributo = identificadorTributo;
	}

	@Column(name = "nombre_tributo", length = 8)
	public String getNombreTributo() {
		return this.nombreTributo;
	}

	public void setNombreTributo(String nombreTributo) {
		this.nombreTributo = nombreTributo;
	}

	@Column(name = "codigo_tipo_tributo", length = 8)
	public String getCodigoTipoTributo() {
		return this.codigoTipoTributo;
	}

	public void setCodigoTipoTributo(String codigoTipoTributo) {
		this.codigoTipoTributo = codigoTipoTributo;
	}

	@Column(name = "base_imponible", precision = 15)
	public BigDecimal getBaseImponible() {
		return this.baseImponible;
	}

	public void setBaseImponible(BigDecimal baseImponible) {
		this.baseImponible = baseImponible;
	}

	@Column(name = "monto_tributo_item", precision = 15)
	public BigDecimal getMontoTributoItem() {
		return this.montoTributoItem;
	}

	public void setMontoTributoItem(BigDecimal montoTributoItem) {
		this.montoTributoItem = montoTributoItem;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "codigo_comprobante", nullable = false)
	public int getCodigoComprobante() {
		return this.codigoComprobante;
	}

	public void setCodigoComprobante(int codigoComprobante) {
		this.codigoComprobante = codigoComprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comprobante", nullable = false, insertable = false, updatable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblComprobante getTblComprobante() {
		return this.tblComprobante;
	}

	public void setTblComprobante(TblComprobante tblComprobante) {
		this.tblComprobante = tblComprobante;
	}

	public void setAuditoriaCreacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(auditoriaBean.getIpCreacion());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			this.setUsuarioCreacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}
	}
	
	public void setAuditoriaModificacion(AuditoriaBean auditoriaBean){
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(auditoriaBean.getIpCreacion());
			
			this.setUsuarioModificacion(auditoriaBean.getCodigoUsuario());
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}
	}

}
